/**
 * Coverage of the API by the MCP server (docs/mcp.md, "Inventaire de l'API").
 *
 * The owner's rule: every action a user can do in Kledg can be done through
 * the MCP server, at the right level, with the same permission checks as
 * the route. Each handler of app/api (method and path) maps to the MCP
 * tools that do what it does, or to a written reason why it stays out of
 * the server. A guard test (lib/mcp/__tests__/route-coverage.test.ts) fails
 * when a route has no entry, when an entry names a tool that does not
 * exist, or when an entry is left for a route that is gone.
 *
 * Reasons are French (they are copied into docs/mcp.md).
 */

export type RouteCoverage =
  /** MCP tools doing what the handler does (several when the route combines steps). */
  | { tools: readonly string[]; note?: string }
  /** Why the handler stays out of the MCP server. */
  | { excluded: ExclusionReason }

/** Why a route stays out of the MCP server. */
export const EXCLUSIONS = {
  auth: 'Authentification du navigateur (Better Auth\u00a0: connexion, sessions, fournisseur OAuth)\u00a0; un assistant se connecte par OAuth ou par clé API.',
  account: 'Compte personnel de l\'utilisateur (identité, mot de passe, sessions, préférences d\'affichage)\u00a0; un assistant n\'agit jamais sur l\'identité ni la sécurité du compte.',
  aiAccess: 'Accès des assistants (clés API, autorisations, mode d\'exécution)\u00a0; un assistant ne peut pas modifier ses propres droits.',
  aiApproval: 'Approbation des actions IA, réservée à la session et au mot de passe de l\'utilisateur dans Kledg (mode validation)\u00a0; un assistant ne peut pas approuver.',
  mcp: 'Le serveur MCP lui-même.',
  cron: 'Tâche planifiée appelée par la plateforme avec son secret, jamais par un utilisateur.',
  health: 'Sonde de disponibilité de l\'instance, sans donnée.',
  instance: 'Administration de l\'instance (utilisateurs, mises à jour, messagerie), hors de toute société\u00a0; reste dans les pages d\'administration.',
  companyDeletion: 'Suppression définitive d\'une société\u00a0: les livres sont conservés 10 ans (Code de commerce art. L123-22)\u00a0; une société qui en tient s\'archive (archive_company), seule une société vide se supprime, dans Kledg.',
  bankConnect: 'Connexion d\'une banque et identifiants des prestataires (consentement et authentification forte à la banque, secrets)\u00a0; restent dans l\'interface.',
  approvalDocuments: 'Documents de l\'approbation des comptes, générés et signés dans Kledg (voir « Ce que le serveur ne fait pas »).',
  managementFeeInvoices: 'Génération des factures de frais de gestion, décision du mainteneur du 2026-10-04 (voir « Ce que le serveur ne fait pas »).',
  ui: 'Préférence ou aide de l\'interface (tableau de bord, menu latéral, liste de démarrage, compteurs, aides de saisie), sans donnée comptable qu\'un autre outil ne donne pas.',
} as const

export type ExclusionReason = keyof typeof EXCLUSIONS

/** Every handler of app/api, as "METHOD /api/path" (dynamic segments as in the folder names). */
export const ROUTE_COVERAGE: Record<string, RouteCoverage> = {
  'GET /api/account/appearance': { excluded: 'account' },
  'PUT /api/account/appearance': { excluded: 'account' },
  'GET /api/account/display-mode': { excluded: 'account' },
  'PUT /api/account/display-mode': { excluded: 'account' },
  'POST /api/account/email': { excluded: 'account' },
  'POST /api/account/password': { excluded: 'account' },
  'PATCH /api/account/profile': { excluded: 'account' },
  'DELETE /api/account': { excluded: 'account' },
  'DELETE /api/account/sessions/[id]': { excluded: 'account' },
  'GET /api/account/sessions': { excluded: 'account' },
  'DELETE /api/account/sessions': { excluded: 'account' },
  'POST /api/accounting-changes': { tools: ['manage_accounting_changes'] },
  'PATCH /api/accounting-changes/[id]': { tools: ['manage_accounting_changes'] },
  'DELETE /api/accounting-changes/[id]': { tools: ['manage_accounting_changes'] },
  'POST /api/accounting-changes/[id]/entry': { tools: ['manage_accounting_changes'] },
  'GET /api/accounting-methods': { tools: ['get_annexe'] },
  'POST /api/accounting-methods': { tools: ['manage_accounting_methods'] },
  'PATCH /api/accounting-methods/[id]': { tools: ['manage_accounting_methods'] },
  'DELETE /api/accounting-methods/[id]': { tools: ['manage_accounting_methods'] },
  'GET /api/accounts/[id]/balance-evolution': { tools: ['get_ledger_report'] },
  'GET /api/accounts/[id]/entries': { tools: ['list_entries'] },
  'GET /api/accounts/[id]': { tools: ['search_accounts'] },
  'DELETE /api/accounts/[id]': { tools: ['manage_accounts'] },
  'PATCH /api/accounts/[id]': { tools: ['manage_accounts'] },
  'GET /api/accounts/check-exists': { tools: ['search_accounts'] },
  'POST /api/accounts/check-pcg-compliance': { tools: ['manage_accounts'] },
  'POST /api/accounts/delete-non-pcg': { tools: ['manage_accounts'] },
  'GET /api/accounts': { tools: ['search_accounts'] },
  'POST /api/accounts': { tools: ['create_account'] },
  'POST /api/accounts/seed-pcg': { tools: ['manage_accounts'] },
  'GET /api/addresses/[id]': { tools: ['get_company_settings'] },
  'GET /api/addresses': { tools: ['get_company_settings'] },
  'POST /api/addresses': { tools: ['manage_company_records'] },
  'PUT /api/ai-access/api-keys/[id]': { excluded: 'aiAccess' },
  'POST /api/ai-access/api-keys': { excluded: 'aiAccess' },
  'PUT /api/ai-access/assistants': { excluded: 'aiAccess' },
  'GET /api/ai-access/grants': { excluded: 'aiAccess' },
  'POST /api/ai-actions/[id]': { excluded: 'aiApproval' },
  'GET /api/ai-actions': { excluded: 'aiApproval' },
  'GET /api/annexe/export': { tools: ['export_report'] },
  'GET /api/annexe': { tools: ['get_annexe'] },
  'PUT /api/annexe': { tools: ['update_annexe_notes'] },
  'GET /api/auth/[...all]': { excluded: 'auth' },
  'POST /api/auth/[...all]': { excluded: 'auth' },
  'PUT /api/banking/accounts/[id]': { tools: ['manage_bank_accounts'] },
  'GET /api/banking/accounts': { tools: ['get_bank_sync_status', 'list_bank_accounts'] },
  'POST /api/banking/accounts/sync': { tools: ['manage_bank_accounts'] },
  'GET /api/banking/attachments/[attachmentId]/proxy': { tools: ['get_file'] },
  'POST /api/banking/attachments/sync': { tools: ['sync_bank_data'] },
  'POST /api/banking/connections/[id]/refresh': { tools: ['sync_bank'] },
  'DELETE /api/banking/connections/[id]': { tools: ['manage_bank_accounts'] },
  'GET /api/banking/connections': { tools: ['get_bank_sync_status'] },
  'POST /api/banking/import-statement': { tools: ['import_statement'] },
  'GET /api/banking/institutions': { excluded: 'bankConnect' },
  'POST /api/banking/manual-accounts': { tools: ['create_bank_account'] },
  'GET /api/banking/missing-receipts': { tools: ['list_missing_receipts'] },
  'POST /api/banking/ponto': { excluded: 'bankConnect' },
  'POST /api/banking/reconciliation/auto-reconcile': { tools: ['bulk_reconcile'] },
  'GET /api/banking/reconciliation': { tools: ['list_bank_transactions', 'list_entries'] },
  'POST /api/banking/reconciliation': { tools: ['reconcile_transaction'] },
  'DELETE /api/banking/reconciliation': { tools: ['unreconcile_transaction'] },
  'POST /api/banking/revolut/authorize': { excluded: 'bankConnect' },
  'GET /api/banking/revolut/callback': { excluded: 'bankConnect' },
  'GET /api/banking/revolut': { excluded: 'bankConnect' },
  'POST /api/banking/revolut': { excluded: 'bankConnect' },
  'POST /api/banking/select-account': { tools: ['manage_bank_accounts'] },
  'PATCH /api/budget-lines/[id]': { tools: ['update_budget_line'] },
  'DELETE /api/budget-lines/[id]': { tools: ['delete_budget_items'] },
  'POST /api/budgets/[id]/lines': { tools: ['create_budget_line'] },
  'GET /api/budgets/[id]/report': { tools: ['get_budget_report'] },
  'GET /api/budgets/[id]': { tools: ['get_budget'] },
  'DELETE /api/budgets/[id]': { tools: ['delete_budget_items'] },
  'GET /api/budgets': { tools: ['list_budgets'] },
  'POST /api/budgets': { tools: ['create_budget'] },
  'GET /api/cash-forecast': { tools: ['get_cash_forecast'] },
  'GET /api/cash-forecast/alert': { tools: ['get_cash_forecast'], note: 'L\'alerte de seuil du tableau de bord est le champ alert de get_cash_forecast.' },
  'GET /api/cash-forecast/export': { tools: ['export_report'] },
  'POST /api/companies/[id]/archive': { tools: ['archive_company'] },
  'DELETE /api/companies/[id]/archive': { tools: ['restore_company'] },
  'GET /api/companies/[id]/balance-sheet/compare': { tools: ['get_balance_sheet'], note: 'Un appel par exercice.' },
  'POST /api/companies/[id]/balance-sheet/config/default': { tools: ['manage_statement_layout'] },
  'GET /api/companies/[id]/balance-sheet/config/history': { tools: ['get_statement_layout'] },
  'POST /api/companies/[id]/balance-sheet/config/history': { tools: ['manage_statement_layout'] },
  'GET /api/companies/[id]/balance-sheet/config/line/[lineId]': { tools: ['get_statement_layout'] },
  'PATCH /api/companies/[id]/balance-sheet/config/line/[lineId]': { tools: ['manage_statement_layout'] },
  'DELETE /api/companies/[id]/balance-sheet/config/line/[lineId]': { tools: ['manage_statement_layout'] },
  'POST /api/companies/[id]/balance-sheet/config/line': { tools: ['manage_statement_layout'] },
  'GET /api/companies/[id]/balance-sheet/config': { tools: ['get_statement_layout'] },
  'POST /api/companies/[id]/balance-sheet/config': { tools: ['manage_statement_layout'] },
  'GET /api/companies/[id]/balance-sheet/config/templates': { tools: ['get_statement_layout'] },
  'POST /api/companies/[id]/balance-sheet/config/templates': { tools: ['manage_statement_layout'] },
  'DELETE /api/companies/[id]/balance-sheet/config/templates/[templateId]': { tools: ['manage_statement_layout'], note: 'Action delete_template.' },
  'GET /api/companies/[id]/balance-sheet/export-excel': { tools: ['export_report'] },
  'GET /api/companies/[id]/balance-sheet/export-pdf': { tools: ['export_report'] },
  'GET /api/companies/[id]/balance-sheet': { tools: ['get_balance_sheet'] },
  'GET /api/companies/[id]/balance-sheet/validate-income-statement': { tools: ['get_balance_sheet', 'get_income_statement'] },
  'POST /api/companies/[id]/corporate-tax/entries': { tools: ['prepare_corporate_tax_entry'] },
  'GET /api/companies/[id]/corporate-tax/export': { tools: ['export_report'] },
  'PUT /api/companies/[id]/corporate-tax/filing': { tools: ['record_tax_filing'] },
  'DELETE /api/companies/[id]/corporate-tax/filing': { tools: ['record_tax_filing'] },
  'PUT /api/companies/[id]/corporate-tax/inputs': { tools: ['save_corporate_tax_inputs'] },
  'GET /api/companies/[id]/corporate-tax': { tools: ['get_corporate_tax'] },
  'GET /api/companies/[id]/cash-forecast-settings': { tools: ['get_company_settings'] },
  'PUT /api/companies/[id]/cash-forecast-settings': { tools: ['update_company_settings'] },
  'GET /api/companies/[id]/remuneration': { tools: ['simulate_remuneration'] },
  'GET /api/companies/[id]/remuneration/export': { tools: ['export_report'] },
  'PUT /api/companies/[id]/remuneration/scenarios': { tools: ['save_remuneration_scenario'] },
  'DELETE /api/companies/[id]/remuneration/scenarios': { tools: ['save_remuneration_scenario'] },
  'POST /api/companies/[id]/remuneration/propose-dividends': { tools: ['save_remuneration_scenario', 'update_year_end_formalities'] },
  'GET /api/companies/[id]/deadline-settings': { tools: ['get_company_settings'] },
  'PUT /api/companies/[id]/deadline-settings': { tools: ['update_company_settings'] },
  'PUT /api/companies/[id]/declarations/status': { tools: ['mark_declaration'] },
  'DELETE /api/companies/[id]/declarations/status': { tools: ['mark_declaration'] },
  'PATCH /api/companies/[id]/establishments/[establishmentId]': { tools: ['manage_company_records'] },
  'DELETE /api/companies/[id]/establishments/[establishmentId]': { tools: ['manage_company_records'] },
  'GET /api/companies/[id]/establishments': { tools: ['get_company_settings'] },
  'POST /api/companies/[id]/establishments': { tools: ['manage_company_records'] },
  'GET /api/companies/[id]/fiscal-years/[fiscalYearId]/approval/documents/[document]': { excluded: 'approvalDocuments' },
  'GET /api/companies/[id]/fiscal-years/[fiscalYearId]/approval': { tools: ['get_year_end_formalities'] },
  'PUT /api/companies/[id]/fiscal-years/[fiscalYearId]/approval': { tools: ['update_year_end_formalities'] },
  'POST /api/companies/[id]/fiscal-years/[fiscalYearId]/close': { tools: ['close_fiscal_year'] },
  'GET /api/companies/[id]/fiscal-years/[fiscalYearId]/close/simulate': { tools: ['close_fiscal_year'], note: 'Aperçu (dryRun) de l\'outil, droit closing:execute comme la route.' },
  'GET /api/companies/[id]/fiscal-years/[fiscalYearId]/depreciation': { tools: ['list_fixed_assets', 'generate_depreciation'], note: 'Dotations à passer\u00a0: aperçu (dryRun) de generate_depreciation.' },
  'POST /api/companies/[id]/fiscal-years/[fiscalYearId]/depreciation': { tools: ['generate_depreciation'] },
  'GET /api/companies/[id]/fiscal-years/[fiscalYearId]/result-allocation': { tools: ['allocate_result'], note: 'Aperçu (dryRun) de l\'outil.' },
  'POST /api/companies/[id]/fiscal-years/[fiscalYearId]/result-allocation': { tools: ['allocate_result'] },
  'GET /api/companies/[id]/fiscal-years/[fiscalYearId]': { tools: ['list_fiscal_years'] },
  'PATCH /api/companies/[id]/fiscal-years/[fiscalYearId]': { tools: ['manage_fiscal_years'] },
  'DELETE /api/companies/[id]/fiscal-years/[fiscalYearId]': { tools: ['manage_fiscal_years'] },
  'POST /api/companies/[id]/fiscal-years/[fiscalYearId]/period-lock': { tools: ['manage_fiscal_years'] },
  'GET /api/companies/[id]/fiscal-years': { tools: ['list_fiscal_years'] },
  'POST /api/companies/[id]/fiscal-years': { tools: ['manage_fiscal_years'] },
  'POST /api/companies/[id]/income-statement/config/default': { tools: ['manage_statement_layout'] },
  'GET /api/companies/[id]/income-statement/config/line/[lineId]': { tools: ['get_statement_layout'] },
  'PATCH /api/companies/[id]/income-statement/config/line/[lineId]': { tools: ['manage_statement_layout'] },
  'DELETE /api/companies/[id]/income-statement/config/line/[lineId]': { tools: ['manage_statement_layout'] },
  'POST /api/companies/[id]/income-statement/config/line': { tools: ['manage_statement_layout'] },
  'GET /api/companies/[id]/income-statement/config': { tools: ['get_statement_layout'] },
  'POST /api/companies/[id]/income-statement/config': { tools: ['manage_statement_layout'] },
  'GET /api/companies/[id]/income-statement/export-excel': { tools: ['export_report'] },
  'GET /api/companies/[id]/income-statement/export-pdf': { tools: ['export_report'] },
  'GET /api/companies/[id]/income-statement': { tools: ['get_income_statement'] },
  'POST /api/companies/[id]/local-taxes/entries': { tools: ['prepare_cfe_entry'] },
  'GET /api/companies/[id]/local-taxes/export': { tools: ['export_report'] },
  'GET /api/companies/[id]/local-taxes': { tools: ['get_local_taxes'] },
  'PUT /api/companies/[id]/local-taxes': { tools: ['save_local_taxes'] },
  'GET /api/companies/[id]/vat-deduction': { tools: ['get_vat_deduction_coefficient'] },
  'PUT /api/companies/[id]/vat-deduction': { tools: ['save_vat_deduction_settings'] },
  'POST /api/companies/[id]/vat-deduction/regularisation': { tools: ['prepare_vat_coefficient_regularisation'] },
  'GET /api/companies/[id]/training-report': { tools: ['get_training_report'] },
  'PUT /api/companies/[id]/training-report': { tools: ['save_training_report'] },
  'PUT /api/companies/[id]/training-report/origins': { tools: ['save_training_origins'] },
  'GET /api/companies/[id]/training-report/export': { tools: ['export_report'] },
  'GET /api/companies/[id]/payroll-tax': { tools: ['get_payroll_tax'] },
  'PUT /api/companies/[id]/payroll-tax': { tools: ['save_payroll_tax'] },
  'POST /api/companies/[id]/payroll-tax/entries': { tools: ['prepare_payroll_tax_entry'] },
  'PATCH /api/companies/[id]/members/[memberId]': { tools: ['manage_members'] },
  'DELETE /api/companies/[id]/members/[memberId]': { tools: ['manage_members'] },
  'GET /api/companies/[id]/members': { tools: ['get_company_settings'] },
  'POST /api/companies/[id]/members': { tools: ['manage_members'] },
  // Leaving a company is the user's own access, like the account routes; manage_members action remove with one's own memberId does it with members:manage.
  'DELETE /api/companies/[id]/membership': { excluded: 'account' },
  'GET /api/companies/[id]/invitations': { tools: ['manage_invitations'] },
  'POST /api/companies/[id]/invitations': { tools: ['manage_invitations'] },
  'DELETE /api/companies/[id]/invitations/[invitationId]': { tools: ['manage_invitations'] },
  'POST /api/companies/[id]/invitations/[invitationId]/resend': { tools: ['manage_invitations'] },
  'GET /api/companies/[id]/onboarding': { excluded: 'ui' },
  'POST /api/companies/[id]/onboarding': { excluded: 'ui' },
  'GET /api/companies/[id]/opening-balances': { tools: ['list_fiscal_years', 'list_entries'] },
  'POST /api/companies/[id]/opening-balances': { tools: ['prepare_opening_balances', 'validate_entries'], note: 'Brouillon, puis validation (entries:validate) comme l\'option validate de la route.' },
  'GET /api/companies/[id]/payment-terms': { tools: ['get_company_settings'] },
  'PUT /api/companies/[id]/payment-terms': { tools: ['update_company_settings'] },
  'GET /api/companies/[id]/persons': { tools: ['get_company_settings'] },
  'POST /api/companies/[id]/persons': { tools: ['manage_company_records'] },
  'GET /api/companies/[id]/persons/[personId]': { tools: ['get_company_settings'] },
  'PATCH /api/companies/[id]/persons/[personId]': { tools: ['manage_company_records'] },
  'DELETE /api/companies/[id]/persons/[personId]': { tools: ['manage_company_records'] },
  'GET /api/companies/[id]': { tools: ['get_company_settings'] },
  'PATCH /api/companies/[id]': { tools: ['update_company_settings'] },
  'DELETE /api/companies/[id]': { excluded: 'companyDeletion' },
  'PATCH /api/companies/[id]/shareholders/[shareholderId]': { tools: ['manage_company_records'] },
  'DELETE /api/companies/[id]/shareholders/[shareholderId]': { tools: ['manage_company_records'] },
  'GET /api/companies/[id]/shareholders': { tools: ['get_company_settings'] },
  'POST /api/companies/[id]/shareholders': { tools: ['manage_company_records'] },
  'GET /api/companies/[id]/sidebar-preferences': { excluded: 'ui' },
  'PUT /api/companies/[id]/sidebar-preferences': { excluded: 'ui' },
  'GET /api/companies/[id]/simple-mode-settings': { tools: ['get_company_settings'] },
  'PUT /api/companies/[id]/simple-mode-settings': { tools: ['update_company_settings'] },
  'GET /api/companies/[id]/simple/counts': { tools: ['list_expenses_to_review'] },
  'GET /api/companies/[id]/tax-regimes': { tools: ['get_company_settings'] },
  'POST /api/companies/[id]/tax-regimes': { tools: ['manage_company_records'] },
  'PATCH /api/companies/[id]/tax-regimes': { tools: ['manage_company_records'] },
  'DELETE /api/companies/[id]/tax-regimes': { tools: ['manage_company_records'] },
  'GET /api/companies/[id]/vat-returns/export': { tools: ['export_report'] },
  'PUT /api/companies/[id]/vat-returns/filing': { tools: ['record_tax_filing'] },
  'DELETE /api/companies/[id]/vat-returns/filing': { tools: ['record_tax_filing'] },
  'GET /api/companies/[id]/vat-returns': { tools: ['get_vat_return'] },
  'POST /api/companies/[id]/vat-returns/settlement': { tools: ['prepare_vat_settlement'] },
  'GET /api/companies/[id]/invoice-numbering': { tools: ['get_company_settings'] },
  'PUT /api/companies/[id]/invoice-numbering': { tools: ['update_company_settings'] },
  'GET /api/companies/[id]/vat-settings': { tools: ['get_company_settings'] },
  'PUT /api/companies/[id]/vat-settings': { tools: ['update_company_settings'] },
  'GET /api/companies/lookup': { tools: ['lookup_siren'] },
  'GET /api/companies': { tools: ['list_companies'] },
  'POST /api/companies': { tools: ['create_company'] },
  'GET /api/cron/sync-banks': { excluded: 'cron' },
  'GET /api/cron/sync-qonto': { excluded: 'cron' },
  'GET /api/cron/period-locks': { excluded: 'cron' },
  'GET /api/dashboard/layout': { excluded: 'ui' },
  'PUT /api/dashboard/layout': { excluded: 'ui' },
  'DELETE /api/dashboard/layout': { excluded: 'ui' },
  'GET /api/dashboard/widgets': { excluded: 'ui' },
  'GET /api/deadlines': { tools: ['list_tax_deadlines'] },
  'POST /api/entries/[id]/duplicate': { tools: ['duplicate_entry'] },
  'POST /api/entries/[id]/reverse': { tools: ['reverse_entry'] },
  'GET /api/entries/[id]': { tools: ['get_entry'] },
  'PATCH /api/entries/[id]': { tools: ['update_draft_entry', 'validate_entries'] },
  'DELETE /api/entries/[id]': { tools: ['delete_draft_entry'] },
  'POST /api/entries/bulk-delete': { tools: ['delete_draft_entry'], note: 'Un appel par brouillon.' },
  'POST /api/entries/bulk-validate': { tools: ['validate_entries'] },
  'GET /api/entries/next-number': { tools: ['validate_entries'], note: 'L\'aperçu (dryRun) donne le numéro de chaque écriture.' },
  'GET /api/entries': { tools: ['list_entries'] },
  'POST /api/entries': { tools: ['create_draft_entry', 'validate_entries'], note: 'Brouillon, puis validation (entries:validate) pour une écriture créée validée.' },
  'PATCH /api/expense-category-rules/[id]': { tools: ['manage_expense_settings'] },
  'DELETE /api/expense-category-rules/[id]': { tools: ['manage_expense_settings'] },
  'GET /api/expense-category-rules': { tools: ['list_expense_category_rules'] },
  'POST /api/expense-category-rules': { tools: ['manage_expense_settings'] },
  'PATCH /api/expense-claimants/[id]': { tools: ['manage_expense_settings'] },
  'DELETE /api/expense-claimants/[id]': { tools: ['manage_expense_settings'] },
  'GET /api/expense-claimants/options': { tools: ['manage_expense_settings'], note: 'Action claimant_options, en lecture.' },
  'GET /api/expense-claimants': { tools: ['list_expense_claimants'] },
  'POST /api/expense-claimants': { tools: ['manage_expense_settings'] },
  'POST /api/expense-reports/[id]/post': { tools: ['manage_expense_report'] },
  'DELETE /api/expense-reports/[id]/post': { tools: ['manage_expense_report'] },
  'GET /api/expense-reports/[id]/reimbursement': { tools: ['manage_expense_report'], note: 'Action reimbursement_candidates, en lecture.' },
  'POST /api/expense-reports/[id]/reimbursement': { tools: ['manage_expense_report'] },
  'GET /api/expense-reports/[id]': { tools: ['get_expense_report'] },
  'PATCH /api/expense-reports/[id]': { tools: ['update_draft_expense_report'] },
  'DELETE /api/expense-reports/[id]': { tools: ['manage_expense_report'] },
  'POST /api/expense-reports/[id]/workflow': { tools: ['manage_expense_report'] },
  'GET /api/expense-reports/receipts': { excluded: 'ui' },
  'GET /api/expense-reports/meal-rule': { tools: ['get_expense_report', 'create_draft_expense_report'] },
  'GET /api/expense-reports': { tools: ['list_expense_reports'] },
  'POST /api/expense-reports': { tools: ['create_draft_expense_report'] },
  'GET /api/fec': { tools: ['export_fec'] },
  'GET /api/fixed-assets/[id]/depreciation-status': { tools: ['list_fixed_assets'] },
  'GET /api/fixed-assets/[id]/depreciation/[entryId]/candidates': { tools: ['list_fixed_assets'] },
  'POST /api/fixed-assets/[id]/depreciation/[entryId]/post': { tools: ['manage_depreciation_record'] },
  'DELETE /api/fixed-assets/[id]/depreciation/[entryId]': { tools: ['manage_depreciation_record'] },
  'PATCH /api/fixed-assets/[id]/depreciation/[entryId]': { tools: ['save_depreciation_record'] },
  'POST /api/fixed-assets/[id]/depreciation': { tools: ['save_depreciation_record'] },
  'GET /api/fixed-assets/[id]': { tools: ['list_fixed_assets'] },
  'PATCH /api/fixed-assets/[id]': { tools: ['manage_fixed_asset'] },
  'DELETE /api/fixed-assets/[id]': { tools: ['manage_fixed_asset'] },
  'GET /api/fixed-assets': { tools: ['list_fixed_assets'] },
  'POST /api/fixed-assets': { tools: ['create_fixed_asset'] },
  'GET /api/fixed-assets/stats': { tools: ['list_fixed_assets'] },
  'GET /api/group/alerts': { tools: ['get_group_alerts'] },
  'GET /api/group/companies': { tools: ['get_group_companies'] },
  'GET /api/group/deadlines': { tools: ['get_group_deadlines'] },
  'GET /api/group/evolution': { tools: ['get_group_evolution'] },
  'GET /api/group/indicators': { tools: ['get_group_indicators'] },
  'GET /api/group/ledger': { tools: ['get_group_ledger'] },
  'GET /api/group/persons': { tools: ['get_group_shareholders'] },
  'GET /api/group/summary': { tools: ['get_group_view', 'get_group_indicators'] },
  'GET /api/group/transactions': { tools: ['list_group_transactions'] },
  'GET /api/group/treasury': { tools: ['get_group_treasury'] },
  'GET /api/group/export': { tools: ['export_report'] },
  'GET /api/group/participations': { tools: ['get_participations'] },
  'GET /api/group/view': { tools: ['get_group_view'] },
  'GET /api/group/structure': { tools: ['get_group_structure'] },
  'GET /api/group/tax': { tools: ['simulate_tax_integration'] },
  'GET /api/group/simple-home': { tools: ['get_group_view', 'get_group_treasury', 'get_group_deadlines', 'get_group_alerts'], note: 'Les mêmes chiffres en mots simples (mode simple de l\'espace groupe).' },
  'GET /api/health': { excluded: 'health' },
  'POST /api/import/preview-fiscal-years': { tools: ['import_accounting_file'], note: 'Aperçu (dryRun) de l\'import.' },
  'POST /api/import': { tools: ['import_accounting_file'] },
  'POST /api/instance/test-email': { excluded: 'instance' },
  'GET /api/integrations/[id]/credentials': { excluded: 'bankConnect' },
  'POST /api/integrations/[id]/features': { excluded: 'bankConnect' },
  'POST /api/integrations/[id]/resources': { excluded: 'bankConnect' },
  'PUT /api/integrations/[id]': { excluded: 'bankConnect' },
  'POST /api/integrations/[id]/sync': { tools: ['sync_bank_data'] },
  'GET /api/integrations': { tools: ['get_bank_sync_status'] },
  'POST /api/integrations': { excluded: 'bankConnect' },
  'POST /api/integrations/sync': { tools: ['sync_bank_data'] },
  'POST /api/integrations/verify': { excluded: 'bankConnect' },
  'PATCH /api/investment-grants/[id]': { tools: ['update_investment_grant'] },
  'DELETE /api/investment-grants/[id]': { tools: ['delete_year_end_items'] },
  'GET /api/investment-grants': { tools: ['get_year_end_inventory'] },
  'POST /api/investment-grants': { tools: ['create_investment_grant'] },
  'GET /api/invoices/[id]/attachment': { tools: ['get_file'] },
  'PATCH /api/invoices/[id]/lines': { tools: ['update_draft_invoice'] },
  'DELETE /api/invoices/[id]/payments/[paymentId]': { tools: ['manage_invoice'] },
  'GET /api/invoices/[id]/payments/candidates': { tools: ['manage_invoice'], note: 'Action payment_candidates, en lecture.' },
  'POST /api/invoices/[id]/payments': { tools: ['manage_invoice'] },
  'POST /api/invoices/[id]/post': { tools: ['manage_invoice'] },
  'DELETE /api/invoices/[id]/post': { tools: ['manage_invoice'] },
  'GET /api/invoices/[id]': { tools: ['get_invoice'] },
  'PATCH /api/invoices/[id]': { tools: ['update_draft_invoice'] },
  'DELETE /api/invoices/[id]': { tools: ['manage_invoice'] },
  'POST /api/invoices/[id]/settle': { tools: ['manage_invoice'] },
  'POST /api/invoices/[id]/qonto': { tools: ['manage_invoice'], note: 'Action resume_qonto.' },
  'POST /api/invoices/import-qonto': { tools: ['import_qonto_invoices'] },
  'GET /api/invoices': { tools: ['list_invoices'] },
  'POST /api/invoices': { tools: ['create_draft_invoice'] },
  'PATCH /api/journals/[id]': { tools: ['manage_journals'] },
  'DELETE /api/journals/[id]': { tools: ['manage_journals'] },
  'POST /api/journals/defaults': { tools: ['manage_journals'] },
  'POST /api/journals': { tools: ['create_journal'] },
  'GET /api/journals': { tools: ['list_journals'] },
  'GET /api/lettering/accounts': { tools: ['list_unlettered_lines'] },
  'POST /api/lettering/auto': { tools: ['auto_letter_account'] },
  'GET /api/lettering': { tools: ['list_unlettered_lines'] },
  'POST /api/lettering': { tools: ['letter_entry_lines'] },
  'GET /api/lettering/suggestions': { tools: ['list_unlettered_lines'] },
  'POST /api/lettering/unletter': { tools: ['unletter_entry_lines'] },
  'GET /api/management-fees/conventions/[id]/invoices': { tools: ['list_management_fee_conventions'] },
  'POST /api/management-fees/conventions/[id]/invoices': { excluded: 'managementFeeInvoices' },
  'GET /api/management-fees/conventions/[id]/preview': { tools: ['preview_management_fees'] },
  'GET /api/management-fees/conventions/[id]': { tools: ['list_management_fee_conventions'] },
  'PATCH /api/management-fees/conventions/[id]': { tools: ['manage_management_fee_convention'] },
  'DELETE /api/management-fees/conventions/[id]': { tools: ['manage_management_fee_convention'] },
  'GET /api/management-fees/conventions': { tools: ['list_management_fee_conventions'] },
  'POST /api/management-fees/conventions': { tools: ['manage_management_fee_convention'] },
  'GET /api/management-fees/subsidiaries': { tools: ['list_management_fee_conventions'] },
  'GET /api/mcp': { excluded: 'mcp' },
  'POST /api/mcp': { excluded: 'mcp' },
  'DELETE /api/mcp': { excluded: 'mcp' },
  'PUT /api/provisions/[id]/assessment': { tools: ['record_provision_assessment'] },
  'DELETE /api/provisions/[id]/assessment': { tools: ['delete_year_end_items'] },
  'PATCH /api/provisions/[id]': { tools: ['update_provision'] },
  'DELETE /api/provisions/[id]': { tools: ['delete_year_end_items'] },
  'POST /api/provisions/doubtful-receivables/reclassify': { tools: ['reclassify_doubtful_receivable'] },
  'GET /api/provisions/doubtful-receivables': { tools: ['list_doubtful_receivables'] },
  'GET /api/provisions': { tools: ['get_year_end_inventory'] },
  'POST /api/provisions': { tools: ['create_provision'] },
  'GET /api/qonto/accounts': { excluded: 'bankConnect' },
  'POST /api/qonto/connect': { excluded: 'bankConnect' },
  'GET /api/qonto/statements/[id]/proxy': { tools: ['get_file'] },
  'GET /api/qonto/statements/[id]': { tools: ['get_qonto_statements'] },
  'GET /api/qonto/statements': { tools: ['get_qonto_statements'] },
  'POST /api/qonto/statements': { tools: ['get_qonto_statements'], note: 'Liste des relevés, filtres dans le corps\u00a0; rien n\'est importé.' },
  'GET /api/qonto/status': { tools: ['get_bank_sync_status'] },
  'POST /api/qonto/test-connection': { excluded: 'bankConnect' },
  'GET /api/qonto/transactions/[id]/attachments': { tools: ['list_qonto_receipts'] },
  'POST /api/qonto/transactions/[id]/attachments/upload': { tools: ['upload_receipt'] },
  'POST /api/qonto/verify': { excluded: 'bankConnect' },
  'GET /api/reports/aged-balance/export-excel': { tools: ['export_report'] },
  'GET /api/reports/aged-balance': { tools: ['get_aged_balance'] },
  'GET /api/reports/auxiliary-balance/export-excel': { tools: ['export_report'] },
  'GET /api/reports/auxiliary-balance': { tools: ['get_auxiliary_balance'] },
  'GET /api/reports/capital-composition': { tools: ['get_capital_composition'] },
  'GET /api/reports/depreciation': { tools: ['list_fixed_assets'] },
  'GET /api/reports/fixed-asset-movements/export': { tools: ['export_report'] },
  'GET /api/reports/fixed-asset-movements': { tools: ['get_fixed_asset_movements'] },
  'GET /api/reports/financial-indicators/export': { tools: ['export_report'] },
  'GET /api/reports/financial-indicators': { tools: ['get_sig', 'get_financial_ratios'] },
  'GET /api/reports/grand-livre': { tools: ['get_ledger_report'] },
  'GET /api/reports/journal/export-excel': { tools: ['export_report'] },
  'GET /api/reports/journal': { tools: ['get_ledger_report'] },
  'GET /api/reports/tiers-flows': { tools: ['get_tiers_flows'] },
  'GET /api/reports/trial-balance': { tools: ['get_trial_balance'] },
  'GET /api/receipts/staged': { excluded: 'ui' },
  'POST /api/receipts/staged': { tools: ['stage_receipt'] },
  'DELETE /api/receipts/staged/[id]': { tools: ['file_receipt'], note: 'Action discard.' },
  'POST /api/receipts/staged/[id]/attach': { tools: ['file_receipt'], note: 'Action attach, à fort impact\u00a0: approuvée dans Kledg sans le contrôle total.' },
  'POST /api/receipts/staged/[id]/expense': { tools: ['file_receipt'], note: 'Action expense, note de frais en brouillon.' },
  'POST /api/receipts/staged/[id]/match': { tools: ['file_receipt'], note: 'Action match.' },
  'GET /api/rule-templates': { tools: ['list_rule_templates'] },
  'GET /api/rule-templates/[id]': { tools: ['list_rule_templates'] },
  'POST /api/rule-templates/[id]/accounts': { tools: ['add_rule_from_template'], note: 'Option createMissingAccounts de l\'outil.' },
  'GET /api/simple/entries': { tools: ['list_entries'] },
  'POST /api/simple/expenses/[id]/confirm': { tools: ['accept_expense_suggestion', 'validate_entries'], note: 'Brouillon, puis validation (entries:validate) quand la société ne demande pas la revue du comptable.' },
  'POST /api/simple/expenses/[id]/receipt': { tools: ['upload_receipt'] },
  'POST /api/simple/expenses/confirm-all': { tools: ['accept_all_expense_suggestions', 'validate_entries'], note: 'Brouillons, puis validation (entries:validate).' },
  'GET /api/simple/expenses': { tools: ['list_expenses_to_review'] },
  'POST /api/subscriptions/budget-item': { tools: ['add_subscription_to_budget'] },
  'PUT /api/subscriptions/decision': { tools: ['classify_subscription'] },
  'GET /api/subscriptions': { tools: ['list_detected_subscriptions'] },
  'GET /api/tasks/count': { excluded: 'ui' },
  'POST /api/tasks/refresh': { tools: ['sync_bank_data'] },
  'GET /api/tiers/[id]': { tools: ['list_tiers'] },
  'PATCH /api/tiers/[id]': { tools: ['manage_tiers'] },
  'DELETE /api/tiers/[id]': { tools: ['delete_tiers'] },
  'POST /api/tiers/attach-auxiliary': { tools: ['manage_tiers'] },
  'GET /api/tiers': { tools: ['list_tiers'] },
  'POST /api/tiers': { tools: ['manage_tiers'] },
  'POST /api/transaction-rules/[id]/duplicate': { tools: ['duplicate_rule'] },
  'PUT /api/transaction-rules/[id]': { tools: ['update_rule'] },
  'DELETE /api/transaction-rules/[id]': { tools: ['delete_rule'] },
  'POST /api/transaction-rules/[id]/simulate': { tools: ['simulate_rule'] },
  'POST /api/transaction-rules/execute': { tools: ['run_rules'] },
  'GET /api/transaction-rules': { tools: ['list_rules'] },
  'POST /api/transaction-rules': { tools: ['create_rule'] },
  'POST /api/transaction-rules/simulate': { tools: ['simulate_rule'] },
  'GET /api/transaction-rules/copy': { tools: ['list_companies', 'list_rules'], note: 'list_rules sur chaque autre société (droit banking:read dans chacune).' },
  'POST /api/transaction-rules/copy': { tools: ['copy_rules_from_company'] },
  'POST /api/transactions/[id]/apply-rule': { tools: ['bulk_reconcile'] },
  'GET /api/transactions/[id]/create-rule': { tools: ['get_transaction_details'] },
  'GET /api/transactions/[id]/reconcile': { tools: ['get_transaction_details'] },
  'POST /api/transactions/[id]/reconcile': { tools: ['reconcile_transaction'] },
  'DELETE /api/transactions/[id]/reconcile': { tools: ['unreconcile_transaction'] },
  'GET /api/transactions/[id]/suggest': { tools: ['get_transaction_details'] },
  'POST /api/transactions/bulk-delete': { tools: ['delete_bank_transactions'] },
  'POST /api/transactions/bulk-reconcile': { tools: ['bulk_reconcile'] },
  'POST /api/transactions/bulk-unreconcile': { tools: ['bulk_reconcile'] },
  'GET /api/transactions': { tools: ['list_bank_transactions'] },
  'PUT /api/updates/channel': { excluded: 'instance' },
  'POST /api/updates/connection': { excluded: 'instance' },
  'DELETE /api/updates/connection': { excluded: 'instance' },
  'GET /api/updates/github': { excluded: 'instance' },
  'GET /api/updates/history': { excluded: 'instance' },
  'POST /api/updates/install': { excluded: 'instance' },
  'POST /api/updates/prepare': { excluded: 'instance' },
  'GET /api/updates': { excluded: 'instance' },
  'GET /api/updates/version': { excluded: 'instance' },
  'PATCH /api/users/[id]': { excluded: 'instance' },
  'DELETE /api/users/[id]': { excluded: 'instance' },
  'GET /api/users': { excluded: 'instance' },
  'POST /api/users': { excluded: 'instance' },
  'POST /api/year-end/entries': { tools: ['prepare_year_end_entries'] },
  'GET /api/year-end': { tools: ['get_year_end_inventory'] },
}
