/**
 * Plan Comptable Général (PCG) français - Version 2026
 * Basé sur le document officiel : Plan-de-comptes-2026.pdf
 * Ce fichier contient la structure complète du PCG 2026 selon les normes de l'ANC
 */
// Basé sur le document officiel : Plan-de-comptes-2026.pdf
// Ce fichier contient la structure complète du PCG 2026 selon les normes de l'ANC

export interface PCGAccount {
  code: string
  label: string
  parentCode?: string
}

// Plan Comptable Général 2026 - Structure complète
export const PCG_ACCOUNTS: PCGAccount[] = [
  // Grandes classes du PCG
  { code: '1', label: 'Comptes de capitaux' },
  { code: '2', label: 'Comptes d\'immobilisations' },
  { code: '3', label: 'Comptes de stocks et en-cours' },
  { code: '4', label: 'Comptes de tiers' },
  { code: '5', label: 'Comptes financiers' },
  { code: '6', label: 'Comptes de charges' },
  { code: '7', label: 'Comptes de produits' },
  
  // Classe 1 - Financement permanent
  { code: '10', label: 'Capital et réserves', parentCode: '1' },
  { code: '101', label: 'Capital', parentCode: '10' },
  { code: '1011', label: 'Capital souscrit - non appelé', parentCode: '101' },
  { code: '1012', label: 'Capital souscrit - appelé non versé', parentCode: '101' },
  { code: '1013', label: 'Capital souscrit - appelé versé', parentCode: '101' },
  { code: '10131', label: 'Capital non amorti', parentCode: '1013' },
  { code: '10132', label: 'Capital amorti', parentCode: '1013' },
  { code: '1018', label: 'Capital souscrit soumis à des réglementations particulières', parentCode: '101' },
  { code: '102', label: 'Fonds fiduciaires', parentCode: '10' },
  { code: '104', label: 'Primes liées au capital', parentCode: '10' },
  { code: '1041', label: 'Primes d\'émission', parentCode: '104' },
  { code: '1042', label: 'Primes de fusion', parentCode: '104' },
  { code: '1043', label: 'Primes d\'apport', parentCode: '104' },
  { code: '1044', label: 'Primes de conversion d\'obligations en actions', parentCode: '104' },
  { code: '1045', label: 'Bons de souscription de titres en capital', parentCode: '104' },
  { code: '105', label: 'Écarts de réévaluation', parentCode: '10' },
  { code: '106', label: 'Réserves', parentCode: '10' },
  { code: '1061', label: 'Réserve légale', parentCode: '106' },
  { code: '1062', label: 'Réserves indisponibles', parentCode: '106' },
  { code: '1063', label: 'Réserves statutaires ou contractuelles', parentCode: '106' },
  { code: '1064', label: 'Réserves réglementées', parentCode: '106' },
  { code: '1068', label: 'Autres réserves', parentCode: '106' },
  { code: '107', label: 'Écart d\'équivalence', parentCode: '10' },
  { code: '108', label: 'Compte de l\'exploitant', parentCode: '10' },
  { code: '109', label: 'Actionnaires : capital souscrit - non appelé', parentCode: '10' },
  { code: '11', label: 'Report à nouveau', parentCode: '1' },
  { code: '110', label: 'Report à nouveau - solde créditeur', parentCode: '11' },
  { code: '119', label: 'Report à nouveau - solde débiteur', parentCode: '11' },
  { code: '12', label: 'Résultat de l\'exercice', parentCode: '1' },
  { code: '120', label: 'Résultat de l\'exercice - bénéfice', parentCode: '12' },
  { code: '1209', label: 'Acomptes sur dividendes', parentCode: '120' },
  { code: '129', label: 'Résultat de l\'exercice - perte', parentCode: '12' },
  { code: '13', label: 'Subventions d\'investissement', parentCode: '1' },
  { code: '131', label: 'Subventions d\'investissement octroyées', parentCode: '13' },
  { code: '139', label: 'Subventions d\'investissement inscrites au compte de résultat', parentCode: '13' },
  { code: '14', label: 'Provisions réglementées', parentCode: '1' },
  { code: '143', label: 'Provisions réglementées pour hausse de prix', parentCode: '14' },
  { code: '145', label: 'Amortissements dérogatoires', parentCode: '14' },
  { code: '148', label: 'Autres provisions réglementées', parentCode: '14' },
  { code: '15', label: 'Provisions', parentCode: '1' },
  { code: '151', label: 'Provisions pour risques', parentCode: '15' },
  { code: '1511', label: 'Provisions pour litiges', parentCode: '151' },
  { code: '1512', label: 'Provisions pour garanties données aux clients', parentCode: '151' },
  { code: '1514', label: 'Provisions pour amendes et pénalités', parentCode: '151' },
  { code: '1515', label: 'Provisions pour pertes de change', parentCode: '151' },
  { code: '1516', label: 'Provisions pour pertes sur contrats', parentCode: '151' },
  { code: '1518', label: 'Autres provisions pour risques', parentCode: '151' },
  { code: '152', label: 'Provisions pour charges', parentCode: '15' },
  { code: '1521', label: 'Provisions pour pensions et obligations similaires', parentCode: '152' },
  { code: '1522', label: 'Provisions pour restructurations', parentCode: '152' },
  { code: '1523', label: 'Provisions pour impôts', parentCode: '152' },
  { code: '1524', label: 'Provisions pour renouvellement des immobilisations - entreprises concessionnaires', parentCode: '152' },
  { code: '1525', label: 'Provisions pour gros entretien ou grandes révisions', parentCode: '152' },
  { code: '1526', label: 'Provisions pour remise en état', parentCode: '152' },
  { code: '1527', label: 'Autres provisions pour charges', parentCode: '152' },
  { code: '16', label: 'Emprunts et dettes assimilées, fonds non remboursables et avances conditionnées', parentCode: '1' },
  { code: '161', label: 'Emprunts obligataires convertibles si non-inscrits dans le compte 167', parentCode: '16' },
  { code: '1618', label: 'Intérêts courus sur emprunts obligataires convertibles', parentCode: '161' },
  { code: '162', label: 'Obligations représentatives de passifs nets remis en fiducie si non-inscrites dans le compte 167', parentCode: '16' },
  { code: '163', label: 'Autres emprunts obligataires si non-inscrits dans le compte 167', parentCode: '16' },
  { code: '1638', label: 'Intérêts courus sur autres emprunts obligataires', parentCode: '163' },
  { code: '164', label: 'Emprunts auprès des établissements de crédit si non-inscrits dans le compte 167', parentCode: '16' },
  { code: '1648', label: 'Intérêts courus sur emprunts auprès des établissements de crédit', parentCode: '164' },
  { code: '165', label: 'Dépôts et cautionnements reçus', parentCode: '16' },
  { code: '1651', label: 'Dépôts', parentCode: '165' },
  { code: '1655', label: 'Cautionnements', parentCode: '165' },
  { code: '1658', label: 'Intérêts courus sur dépôts et cautionnements reçus', parentCode: '165' },
  { code: '166', label: 'Participation des salariés aux résultats', parentCode: '16' },
  { code: '1661', label: 'Comptes bloqués', parentCode: '166' },
  { code: '1662', label: 'Fonds de participation', parentCode: '166' },
  { code: '1668', label: 'Intérêts courus sur participation des salariés aux résultats', parentCode: '166' },
  { code: '167', label: 'Fonds non remboursables et avances conditionnées', parentCode: '16' },
  { code: '1671', label: 'Fonds non remboursables montant principal', parentCode: '167' },
  { code: '16711', label: 'Titres participatifs montant principal', parentCode: '1671' },
  { code: '16712', label: 'Autres fonds non remboursables montant principal', parentCode: '1671' },
  { code: '1673', label: 'Avances conditionnées montant principal', parentCode: '167' },
  { code: '1674', label: 'Avances conditionnées intérêts courus', parentCode: '167' },
  { code: '168', label: 'Autres emprunts et dettes assimilées', parentCode: '16' },
  { code: '1681', label: 'Autres emprunts', parentCode: '168' },
  { code: '1682', label: 'Emprunts participatifs', parentCode: '168' },
  { code: '1685', label: 'Rentes viagères capitalisées', parentCode: '168' },
  { code: '1687', label: 'Autres dettes', parentCode: '168' },
  { code: '1688', label: 'Intérêts courus sur autres emprunts et dettes assimilées', parentCode: '168' },
  { code: '169', label: 'Primes de remboursement des emprunts', parentCode: '16' },
  { code: '17', label: 'Dettes rattachées à des participations', parentCode: '1' },
  { code: '171', label: 'Dettes rattachées à des participations - groupe', parentCode: '17' },
  { code: '174', label: 'Dettes rattachées à des participations - hors groupe', parentCode: '17' },
  { code: '178', label: 'Dettes rattachées à des sociétés en participation', parentCode: '17' },
  { code: '18', label: 'Comptes de liaison des établissements et sociétés en participation', parentCode: '1' },
  { code: '181', label: 'Comptes de liaison des établissements', parentCode: '18' },
  { code: '186', label: 'Biens et prestations de services échangés entre établissements - charges', parentCode: '18' },
  { code: '187', label: 'Biens et prestations de services échangés entre établissements - produits', parentCode: '18' },
  { code: '188', label: 'Comptes de liaison des sociétés en participation', parentCode: '18' },

  // Classe 2 - Actif immobilisé
  { code: '20', label: 'Immobilisations incorporelles', parentCode: '2' },
  { code: '201', label: 'Frais d\'établissement', parentCode: '20' },
  { code: '2011', label: 'Frais de constitution', parentCode: '201' },
  { code: '2012', label: 'Frais de premier établissement', parentCode: '201' },
  { code: '20121', label: 'Frais de prospection', parentCode: '2012' },
  { code: '20122', label: 'Frais de publicité', parentCode: '2012' },
  { code: '2013', label: 'Frais d\'augmentation de capital et d\'opérations diverses - fusions, scissions, transformations', parentCode: '201' },
  { code: '203', label: 'Frais de développement', parentCode: '20' },
  { code: '205', label: 'Concessions et droits similaires, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires', parentCode: '20' },
  { code: '206', label: 'Droit au bail', parentCode: '20' },
  { code: '207', label: 'Fonds commercial', parentCode: '20' },
  { code: '208', label: 'Autres immobilisations incorporelles', parentCode: '20' },
  { code: '2081', label: 'Mali de fusion sur actifs incorporels', parentCode: '208' },
  { code: '21', label: 'Immobilisations corporelles', parentCode: '2' },
  { code: '211', label: 'Terrains', parentCode: '21' },
  { code: '2111', label: 'Terrains nus', parentCode: '211' },
  { code: '2112', label: 'Terrains aménagés', parentCode: '211' },
  { code: '2113', label: 'Sous-sols et sur-sols', parentCode: '211' },
  { code: '2114', label: 'Terrains de carrières (Tréfonds)', parentCode: '211' },
  { code: '2115', label: 'Terrains bâtis', parentCode: '211' },
  { code: '212', label: 'Agencements et aménagements de terrains', parentCode: '21' },
  { code: '213', label: 'Constructions', parentCode: '21' },
  { code: '2131', label: 'Bâtiments', parentCode: '213' },
  { code: '2135', label: 'Installations générales - agencements - aménagements des constructions', parentCode: '213' },
  { code: '2138', label: 'Ouvrages d\'infrastructure', parentCode: '213' },
  { code: '214', label: 'Constructions sur sol d\'autrui', parentCode: '21' },
  { code: '215', label: 'Installations techniques, matériels et outillages industriels', parentCode: '21' },
  { code: '2151', label: 'Installations complexes spécialisées', parentCode: '215' },
  { code: '21511', label: 'Installations complexes spécialisées sur sol propre', parentCode: '2151' },
  { code: '21514', label: 'Installations complexes spécialisées sur sol d\'autrui', parentCode: '2151' },
  { code: '2153', label: 'Installations à caractère spécifique', parentCode: '215' },
  { code: '21531', label: 'Installations à caractère spécifique sur sol propre', parentCode: '2153' },
  { code: '21534', label: 'Installations à caractère spécifique sur sol d\'autrui', parentCode: '2153' },
  { code: '2154', label: 'Matériels industriels', parentCode: '215' },
  { code: '2155', label: 'Outillages industriels', parentCode: '215' },
  { code: '2157', label: 'Agencements et aménagements des matériels et outillages industriels', parentCode: '215' },
  { code: '218', label: 'Autres immobilisations corporelles', parentCode: '21' },
  { code: '2181', label: 'Installations générales, agencements, aménagements divers', parentCode: '218' },
  { code: '2182', label: 'Matériel de transport', parentCode: '218' },
  { code: '2183', label: 'Matériel de bureau et matériel informatique', parentCode: '218' },
  { code: '2184', label: 'Mobilier', parentCode: '218' },
  { code: '2185', label: 'Cheptel', parentCode: '218' },
  { code: '2186', label: 'Emballages récupérables', parentCode: '218' },
  { code: '2187', label: 'Mali de fusion sur actifs corporels', parentCode: '218' },
  { code: '22', label: 'Immobilisations mises en concession', parentCode: '2' },
  { code: '229', label: 'Droits du concédant', parentCode: '22' },
  { code: '23', label: 'Immobilisations en cours, avances et acomptes', parentCode: '2' },
  { code: '231', label: 'Immobilisations corporelles en cours', parentCode: '23' },
  { code: '232', label: 'Immobilisations incorporelles en cours', parentCode: '23' },
  { code: '237', label: 'Avances et acomptes versés sur commandes d\'immobilisations incorporelles', parentCode: '23' },
  { code: '238', label: 'Avances et acomptes versés sur commandes d\'immobilisations corporelles', parentCode: '23' },
  { code: '26', label: 'Participations et créances rattachées à des participations', parentCode: '2' },
  { code: '261', label: 'Titres de participation', parentCode: '26' },
  { code: '2611', label: 'Actions', parentCode: '261' },
  { code: '2618', label: 'Autres titres', parentCode: '261' },
  { code: '262', label: 'Titres évalués par équivalence', parentCode: '26' },
  { code: '266', label: 'Autres formes de participation', parentCode: '26' },
  { code: '2661', label: 'Droits représentatifs d\'actifs nets remis en fiducie', parentCode: '266' },
  { code: '267', label: 'Créances rattachées à des participations', parentCode: '26' },
  { code: '2671', label: 'Créances rattachées à des participations - groupe', parentCode: '267' },
  { code: '2674', label: 'Créances rattachées à des participations - hors groupe', parentCode: '267' },
  { code: '2675', label: 'Versements représentatifs d\'apports non capitalisés - appel de fonds', parentCode: '267' },
  { code: '2676', label: 'Avances consolidables', parentCode: '267' },
  { code: '2677', label: 'Autres créances rattachées à des participations', parentCode: '267' },
  { code: '2678', label: 'Intérêts courus', parentCode: '267' },
  { code: '268', label: 'Créances rattachées à des sociétés en participation', parentCode: '26' },
  { code: '2681', label: 'Principal', parentCode: '268' },
  { code: '2688', label: 'Intérêts courus', parentCode: '268' },
  { code: '269', label: 'Versements restant à effectuer sur titres de participation non libérés', parentCode: '26' },
  { code: '27', label: 'Autres immobilisations financières', parentCode: '2' },
  { code: '271', label: 'Titres immobilisés autres que les titres immobilisés de l\'activité de portefeuille (droit de propriété)', parentCode: '27' },
  { code: '2711', label: 'Actions', parentCode: '271' },
  { code: '2718', label: 'Autres titres', parentCode: '271' },
  { code: '272', label: 'Titres immobilisés (droit de créance)', parentCode: '27' },
  { code: '2721', label: 'Obligations', parentCode: '272' },
  { code: '2722', label: 'Bons', parentCode: '272' },
  { code: '273', label: 'Titres immobilisés de l\'activité de portefeuille', parentCode: '27' },
  { code: '274', label: 'Prêts', parentCode: '27' },
  { code: '2741', label: 'Prêts participatifs', parentCode: '274' },
  { code: '2742', label: 'Prêts aux associés', parentCode: '274' },
  { code: '2743', label: 'Prêts au personnel', parentCode: '274' },
  { code: '2748', label: 'Autres prêts', parentCode: '274' },
  { code: '275', label: 'Dépôts et cautionnements versés', parentCode: '27' },
  { code: '2751', label: 'Dépôts', parentCode: '275' },
  { code: '2755', label: 'Cautionnements', parentCode: '275' },
  { code: '276', label: 'Autres créances immobilisées', parentCode: '27' },
  { code: '2761', label: 'Créances diverses', parentCode: '276' },
  { code: '2768', label: 'Intérêts courus', parentCode: '276' },
  { code: '27682', label: 'Intérêts courus sur titres immobilisés (droit de créance)', parentCode: '2768' },
  { code: '27684', label: 'Intérêts courus sur prêts', parentCode: '2768' },
  { code: '27685', label: 'Intérêts courus sur dépôts et cautionnements', parentCode: '2768' },
  { code: '27688', label: 'Intérêts courus sur créances diverses', parentCode: '2768' },
  { code: '277', label: 'Actions propres ou parts propres', parentCode: '27' },
  { code: '2771', label: 'Actions propres ou parts propres', parentCode: '277' },
  { code: '2772', label: 'Actions propres ou parts propres en voie d\'annulation', parentCode: '277' },
  { code: '278', label: 'Mali de fusion sur actifs financiers', parentCode: '27' },
  { code: '279', label: 'Versements restant à effectuer sur titres immobilisés non libérés', parentCode: '27' },
  { code: '28', label: 'Amortissements des immobilisations', parentCode: '2' },
  { code: '280', label: 'Amortissements des immobilisations incorporelles et des frais d\'établissement', parentCode: '28' },
  { code: '2801', label: 'Frais d\'établissement', parentCode: '280' },
  { code: '2803', label: 'Frais de développement', parentCode: '280' },
  { code: '2805', label: 'Concessions et droits similaires, brevets, licences, solutions informatiques, droits et valeurs similaires', parentCode: '280' },
  { code: '2806', label: 'Droit au bail', parentCode: '280' },
  { code: '2807', label: 'Fonds commercial', parentCode: '280' },
  { code: '2808', label: 'Autres immobilisations incorporelles', parentCode: '280' },
  { code: '281', label: 'Amortissements des immobilisations corporelles', parentCode: '28' },
  { code: '2812', label: 'Agencements, aménagements de terrains', parentCode: '281' },
  { code: '2813', label: 'Constructions', parentCode: '281' },
  { code: '2814', label: 'Constructions sur sol d\'autrui', parentCode: '281' },
  { code: '2815', label: 'Installations, matériel et outillage industriels', parentCode: '281' },
  { code: '2818', label: 'Autres immobilisations corporelles', parentCode: '281' },
  { code: '28187', label: 'Amortissement du mali de fusion sur actifs corporels', parentCode: '2818' },
  { code: '282', label: 'Amortissements des immobilisations mises en concession', parentCode: '28' },
  { code: '29', label: 'Dépréciations des immobilisations', parentCode: '2' },
  { code: '290', label: 'Dépréciations des immobilisations incorporelles', parentCode: '29' },
  { code: '2901', label: 'Frais d\'établissement', parentCode: '290' },
  { code: '2903', label: 'Frais de développement', parentCode: '290' },
  { code: '2905', label: 'Marques, procédés, droits et valeurs similaires', parentCode: '290' },
  { code: '2906', label: 'Droit au bail', parentCode: '290' },
  { code: '2907', label: 'Fonds commercial', parentCode: '290' },
  { code: '2908', label: 'Autres immobilisations incorporelles', parentCode: '290' },
  { code: '29081', label: 'Dépréciation du mali de fusion sur actifs incorporels', parentCode: '2908' },
  { code: '291', label: 'Dépréciations des immobilisations corporelles', parentCode: '29' },
  { code: '2911', label: 'Terrains', parentCode: '291' },
  { code: '2912', label: 'Agencements et aménagements de terrains', parentCode: '291' },
  { code: '2913', label: 'Constructions', parentCode: '291' },
  { code: '2914', label: 'Constructions sur sol d\'autrui', parentCode: '291' },
  { code: '2915', label: 'Installations techniques, matériels et outillages industriels', parentCode: '291' },
  { code: '2918', label: 'Autres immobilisations corporelles', parentCode: '291' },
  { code: '29187', label: 'Dépréciation du mali de fusion sur actifs corporels', parentCode: '2918' },
  { code: '292', label: 'Dépréciations des immobilisations mises en concession', parentCode: '29' },
  { code: '293', label: 'Dépréciations des immobilisations en cours', parentCode: '29' },
  { code: '2931', label: 'Immobilisations corporelles en cours', parentCode: '293' },
  { code: '2932', label: 'Immobilisations incorporelles en cours', parentCode: '293' },
  { code: '296', label: 'Dépréciations des participations et créances rattachées à des participations', parentCode: '29' },
  { code: '2961', label: 'Titres de participation', parentCode: '296' },
  { code: '2962', label: 'Titres évalués par équivalence', parentCode: '296' },
  { code: '2966', label: 'Autres formes de participation', parentCode: '296' },
  { code: '2967', label: 'Créances rattachées à des participations', parentCode: '296' },
  { code: '2968', label: 'Créances rattachées à des sociétés en participation', parentCode: '296' },
  { code: '297', label: 'Dépréciations des autres immobilisations financières', parentCode: '29' },
  { code: '2971', label: 'Titres immobilisés autres que les titres immobilisés de l\'activité de portefeuille (droit de propriété)', parentCode: '297' },
  { code: '2972', label: 'Titres immobilisés (droit de créance)', parentCode: '297' },
  { code: '2973', label: 'Titres immobilisés de l\'activité de portefeuille', parentCode: '297' },
  { code: '2974', label: 'Prêts', parentCode: '297' },
  { code: '2975', label: 'Dépôts et cautionnements versés', parentCode: '297' },
  { code: '2976', label: 'Autres créances immobilisées', parentCode: '297' },

  // Classe 3 - Stocks et en-cours
  { code: '31', label: 'Matières premières et fournitures', parentCode: '3' },
  { code: '32', label: 'Autres approvisionnements', parentCode: '3' },
  { code: '321', label: 'Matières consommables', parentCode: '32' },
  { code: '322', label: 'Fournitures consommables', parentCode: '32' },
  { code: '3221', label: 'Combustibles', parentCode: '322' },
  { code: '3222', label: 'Produits d\'entretien', parentCode: '322' },
  { code: '3223', label: 'Fournitures d\'atelier et d\'usine', parentCode: '322' },
  { code: '3224', label: 'Fournitures de magasin', parentCode: '322' },
  { code: '3225', label: 'Fournitures de bureau', parentCode: '322' },
  { code: '326', label: 'Emballages', parentCode: '32' },
  { code: '3261', label: 'Emballages perdus', parentCode: '326' },
  { code: '3265', label: 'Emballages récupérables non identifiables', parentCode: '326' },
  { code: '3267', label: 'Emballages à usage mixte', parentCode: '326' },
  { code: '33', label: 'En-cours de production de biens', parentCode: '3' },
  { code: '331', label: 'Produits en cours', parentCode: '33' },
  { code: '335', label: 'Travaux en cours', parentCode: '33' },
  { code: '34', label: 'En-cours de production de services', parentCode: '3' },
  { code: '341', label: 'Études en cours', parentCode: '34' },
  { code: '345', label: 'Prestations de services en cours', parentCode: '34' },
  { code: '35', label: 'Stocks de produits', parentCode: '3' },
  { code: '351', label: 'Produits intermédiaires', parentCode: '35' },
  { code: '355', label: 'Produits finis', parentCode: '35' },
  { code: '358', label: 'Produits résiduels ou matières de récupération', parentCode: '35' },
  { code: '3581', label: 'Déchets', parentCode: '358' },
  { code: '3585', label: 'Rebut', parentCode: '358' },
  { code: '3586', label: 'Matières de récupération', parentCode: '358' },
  { code: '36', label: 'Stocks provenant d\'immobilisations', parentCode: '3' },
  { code: '37', label: 'Stocks de marchandises', parentCode: '3' },
  { code: '38', label: 'Stocks en voie d\'acheminement, mis en dépôt ou donnés en consignation', parentCode: '3' },
  { code: '39', label: 'Dépréciations des stocks et en-cours', parentCode: '3' },
  { code: '391', label: 'Dépréciations des matières premières et fournitures', parentCode: '39' },
  { code: '392', label: 'Dépréciations des autres approvisionnements', parentCode: '39' },
  { code: '393', label: 'Dépréciations des en-cours de production de biens', parentCode: '39' },
  { code: '394', label: 'Dépréciations des en-cours de production de services', parentCode: '39' },
  { code: '395', label: 'Dépréciations des stocks de produits', parentCode: '39' },
  { code: '397', label: 'Dépréciations des stocks de marchandises', parentCode: '39' },

  // Classe 4 - Comptes de tiers
  { code: '40', label: 'Fournisseurs et comptes rattachés', parentCode: '4' },
  { code: '401', label: 'Fournisseurs', parentCode: '40' },
  { code: '4011', label: 'Fournisseurs - Achats de biens et prestations de services', parentCode: '401' },
  { code: '4017', label: 'Fournisseurs - Retenues de garantie', parentCode: '401' },
  { code: '403', label: 'Fournisseurs - Effets à payer', parentCode: '40' },
  { code: '404', label: 'Fournisseurs d\'immobilisations', parentCode: '40' },
  { code: '4041', label: 'Fournisseurs - Achats d\'immobilisations', parentCode: '404' },
  { code: '4047', label: 'Fournisseurs d\'immobilisations - Retenues de garantie', parentCode: '404' },
  { code: '405', label: 'Fournisseurs d\'immobilisations - Effets à payer', parentCode: '40' },
  { code: '408', label: 'Fournisseurs - Factures non parvenues', parentCode: '40' },
  { code: '4081', label: 'Fournisseurs', parentCode: '408' },
  { code: '4084', label: 'Fournisseurs d\'immobilisations', parentCode: '408' },
  { code: '4088', label: 'Fournisseurs - Intérêts courus', parentCode: '408' },
  { code: '409', label: 'Fournisseurs débiteurs', parentCode: '40' },
  { code: '4091', label: 'Fournisseurs - Avances et acomptes versés sur commandes', parentCode: '409' },
  { code: '4096', label: 'Fournisseurs - Créances pour emballages et matériel à rendre', parentCode: '409' },
  { code: '4097', label: 'Fournisseurs - Autres avoirs', parentCode: '409' },
  { code: '40971', label: 'Fournisseurs d\'exploitation', parentCode: '4097' },
  { code: '40974', label: 'Fournisseurs d\'immobilisations', parentCode: '4097' },
  { code: '4098', label: 'Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus', parentCode: '409' },
  { code: '41', label: 'Clients et comptes rattachés', parentCode: '4' },
  { code: '411', label: 'Clients', parentCode: '41' },
  { code: '4111', label: 'Clients - Ventes de biens ou de prestations de services', parentCode: '411' },
  { code: '4117', label: 'Clients - Retenues de garantie', parentCode: '411' },
  { code: '413', label: 'Clients - Effets à recevoir', parentCode: '41' },
  { code: '416', label: 'Clients douteux ou litigieux', parentCode: '41' },
  { code: '418', label: 'Clients - Produits non encore facturés', parentCode: '41' },
  { code: '4181', label: 'Clients - Factures à établir', parentCode: '418' },
  { code: '4188', label: 'Clients - Intérêts courus', parentCode: '418' },
  { code: '419', label: 'Clients créditeurs', parentCode: '41' },
  { code: '4191', label: 'Clients - Avances et acomptes reçus sur commandes', parentCode: '419' },
  { code: '4196', label: 'Clients - Dettes sur emballages et matériels consignés', parentCode: '419' },
  { code: '4197', label: 'Clients - Autres avoirs', parentCode: '419' },
  { code: '4198', label: 'Rabais, remises, ristournes à accorder et autres avoirs à établir', parentCode: '419' },
  { code: '42', label: 'Personnel et comptes rattachés', parentCode: '4' },
  { code: '421', label: 'Personnel - Rémunérations dues', parentCode: '42' },
  { code: '422', label: 'Comité social et économique', parentCode: '42' },
  { code: '424', label: 'Participation des salariés aux résultats', parentCode: '42' },
  { code: '4246', label: 'Réserve spéciale', parentCode: '424' },
  { code: '4248', label: 'Comptes courants', parentCode: '424' },
  { code: '425', label: 'Personnel - Avances et acomptes et autres comptes débiteurs', parentCode: '42' },
  { code: '426', label: 'Personnel - Dépôts', parentCode: '42' },
  { code: '427', label: 'Personnel - Oppositions', parentCode: '42' },
  { code: '428', label: 'Personnel - Charges à payer', parentCode: '42' },
  { code: '4282', label: 'Dettes provisionnées pour congés à payer', parentCode: '428' },
  { code: '4284', label: 'Dettes provisionnées pour participation des salariés aux résultats', parentCode: '428' },
  { code: '4286', label: 'Autres charges à payer', parentCode: '428' },
  { code: '43', label: 'Sécurité sociale et autres organismes sociaux', parentCode: '4' },
  { code: '431', label: 'Sécurité sociale', parentCode: '43' },
  { code: '437', label: 'Autres organismes sociaux', parentCode: '43' },
  { code: '438', label: 'Organismes sociaux - Charges à payer', parentCode: '43' },
  { code: '4382', label: 'Charges sociales sur congés à payer', parentCode: '438' },
  { code: '4386', label: 'Autres charges à payer', parentCode: '438' },
  { code: '439', label: 'Organismes sociaux - Produits à recevoir', parentCode: '43' },
  { code: '44', label: 'État et autres collectivités publiques', parentCode: '4' },
  { code: '441', label: 'État - Subventions et aides à recevoir', parentCode: '44' },
  { code: '442', label: 'Contributions, impôts et taxes recouvrés pour le compte de l\'État', parentCode: '44' },
  { code: '4421', label: 'Prélèvements à la source (Impôt sur le revenu)', parentCode: '442' },
  { code: '4422', label: 'Prélèvements forfaitaires non libératoires', parentCode: '442' },
  { code: '4423', label: 'Retenues et prélèvements sur les distributions', parentCode: '442' },
  { code: '444', label: 'État - Impôts sur les bénéfices', parentCode: '44' },
  { code: '445', label: 'État - Taxes sur le chiffre d\'affaires', parentCode: '44' },
  { code: '4452', label: 'TVA due intracommunautaire', parentCode: '445' },
  { code: '4455', label: 'Taxes sur le chiffre d\'affaires à décaisser', parentCode: '445' },
  { code: '44551', label: 'TVA à décaisser', parentCode: '4455' },
  { code: '44558', label: 'Taxes assimilées à la TVA', parentCode: '4455' },
  { code: '4456', label: 'Taxes sur le chiffre d\'affaires déductibles', parentCode: '445' },
  { code: '44562', label: 'TVA sur immobilisations', parentCode: '4456' },
  { code: '44563', label: 'TVA transférée par d\'autres entités', parentCode: '4456' },
  { code: '44566', label: 'TVA sur autres biens et services', parentCode: '4456' },
  { code: '44567', label: 'Crédit de TVA à reporter', parentCode: '4456' },
  { code: '44568', label: 'Taxes assimilées à la TVA', parentCode: '4456' },
  { code: '4457', label: 'Taxes sur le chiffre d\'affaires collectées', parentCode: '445' },
  { code: '44571', label: 'TVA collectée', parentCode: '4457' },
  { code: '44578', label: 'Taxes assimilées à la TVA', parentCode: '4457' },
  { code: '4458', label: 'Taxes sur le chiffre d\'affaires à régulariser ou en attente', parentCode: '445' },
  { code: '44581', label: 'Acomptes - Régime simplifié d\'imposition', parentCode: '4458' },
  { code: '44583', label: 'Remboursement de taxes sur le chiffre d\'affaires demandé', parentCode: '4458' },
  { code: '44584', label: 'TVA récupérée d\'avance', parentCode: '4458' },
  { code: '44586', label: 'Taxes sur le chiffre d\'affaires sur factures non parvenues', parentCode: '4458' },
  { code: '44587', label: 'Taxes sur le chiffre d\'affaires sur factures à établir', parentCode: '4458' },
  { code: '446', label: 'Obligations cautionnées', parentCode: '44' },
  { code: '447', label: 'Autres impôts, taxes et versements assimilés', parentCode: '44' },
  { code: '448', label: 'État - Charges à payer et produits à recevoir', parentCode: '44' },
  { code: '4481', label: 'État - Charges à payer', parentCode: '448' },
  { code: '44811', label: 'Charges fiscales sur congés à payer', parentCode: '4481' },
  { code: '44812', label: 'Charges à payer', parentCode: '4481' },
  { code: '4482', label: 'État - Produits à recevoir', parentCode: '448' },
  { code: '449', label: 'Quotas d\'émission à acquérir', parentCode: '44' },
  { code: '45', label: 'Groupe et associés', parentCode: '4' },
  { code: '451', label: 'Groupe', parentCode: '45' },
  { code: '455', label: 'Associés - Comptes courants', parentCode: '45' },
  { code: '4551', label: 'Principal', parentCode: '455' },
  { code: '4558', label: 'Intérêts courus', parentCode: '455' },
  { code: '456', label: 'Associés - Opérations sur le capital', parentCode: '45' },
  { code: '4561', label: 'Associés - Comptes d\'apport en société', parentCode: '456' },
  { code: '45611', label: 'Apports en nature', parentCode: '4561' },
  { code: '45615', label: 'Apports en numéraire', parentCode: '4561' },
  { code: '4562', label: 'Apporteurs - Capital appelé, non versé', parentCode: '456' },
  { code: '45621', label: 'Actionnaires - Capital souscrit et appelé, non versé', parentCode: '4562' },
  { code: '45625', label: 'Associés - Capital appelé, non versé', parentCode: '4562' },
  { code: '4563', label: 'Associés - Versements reçus sur augmentation de capital', parentCode: '456' },
  { code: '4564', label: 'Associés - Versements anticipés', parentCode: '456' },
  { code: '4566', label: 'Actionnaires défaillants', parentCode: '456' },
  { code: '4567', label: 'Associés - Capital à rembourser', parentCode: '456' },
  { code: '457', label: 'Associés - Dividendes à payer', parentCode: '45' },
  { code: '458', label: 'Associés - Opérations faites en commun et en GIE', parentCode: '45' },
  { code: '4581', label: 'Opérations courantes', parentCode: '458' },
  { code: '4588', label: 'Intérêts courus', parentCode: '458' },
  { code: '46', label: 'Débiteurs divers et créditeurs divers', parentCode: '4' },
  { code: '462', label: 'Créances sur cessions d\'immobilisations', parentCode: '46' },
  { code: '464', label: 'Dettes sur acquisitions de valeurs mobilières de placement', parentCode: '46' },
  { code: '465', label: 'Créances sur cessions de valeurs mobilières de placement', parentCode: '46' },
  { code: '467', label: 'Divers comptes débiteurs et produits à recevoir', parentCode: '46' },
  { code: '468', label: 'Divers comptes créditeurs et charges à payer', parentCode: '46' },
  { code: '47', label: 'Comptes transitoires ou d\'attente', parentCode: '4' },
  { code: '471', label: 'Comptes d\'attente', parentCode: '47' },
  { code: '472', label: 'Comptes d\'attente', parentCode: '47' },
  { code: '473', label: 'Comptes d\'attente', parentCode: '47' },
  { code: '474', label: 'Différences d\'évaluation - Actif', parentCode: '47' },
  { code: '4741', label: 'Différences d\'évaluation sur instruments financiers à terme - Actif', parentCode: '474' },
  { code: '4742', label: 'Différences d\'évaluation sur jetons détenus - Actif', parentCode: '474' },
  { code: '4746', label: 'Différences d\'évaluation de jetons sur des passifs - Actif', parentCode: '474' },
  { code: '475', label: 'Différences d\'évaluation - Passif', parentCode: '47' },
  { code: '4751', label: 'Différences d\'évaluation sur instruments financiers à terme - Passif', parentCode: '475' },
  { code: '4752', label: 'Différences d\'évaluation sur jetons détenus - Passif', parentCode: '475' },
  { code: '4756', label: 'Différences d\'évaluation de jetons sur des passifs - Passif', parentCode: '475' },
  { code: '476', label: 'Différence de conversion - Actif', parentCode: '47' },
  { code: '4761', label: 'Diminution des créances', parentCode: '476' },
  { code: '4762', label: 'Augmentation des dettes', parentCode: '476' },
  { code: '4768', label: 'Différences compensées par couverture de change', parentCode: '476' },
  { code: '477', label: 'Différences de conversion - Passif', parentCode: '47' },
  { code: '4771', label: 'Augmentation des créances', parentCode: '477' },
  { code: '4772', label: 'Diminution des dettes', parentCode: '477' },
  { code: '4778', label: 'Différences compensées par couverture de change', parentCode: '477' },
  { code: '478', label: 'Autres comptes transitoires', parentCode: '47' },
  { code: '4781', label: 'Mali de fusion sur actif circulant', parentCode: '478' },
  { code: '48', label: 'Comptes de régularisation', parentCode: '4' },
  { code: '481', label: 'Frais d\'émission des emprunts', parentCode: '48' },
  { code: '486', label: 'Charges constatées d\'avance', parentCode: '48' },
  { code: '487', label: 'Produits constatés d\'avance', parentCode: '48' },
  { code: '4871', label: 'Produits constatés d\'avance sur jetons émis', parentCode: '487' },
  { code: '488', label: 'Comptes de répartition périodique des charges et des produits', parentCode: '48' },
  { code: '4886', label: 'Charges', parentCode: '488' },
  { code: '4887', label: 'Produits', parentCode: '488' },
  { code: '49', label: 'Dépréciations des comptes de tiers', parentCode: '4' },
  { code: '491', label: 'Dépréciations des comptes de clients', parentCode: '49' },
  { code: '495', label: 'Dépréciations des comptes du groupe et des associés', parentCode: '49' },
  { code: '4951', label: 'Comptes du groupe', parentCode: '495' },
  { code: '4955', label: 'Comptes courants des associés', parentCode: '495' },
  { code: '4958', label: 'Opérations faites en commun et en GIE', parentCode: '495' },
  { code: '496', label: 'Dépréciations des comptes de débiteurs divers', parentCode: '49' },
  { code: '4962', label: 'Créances sur cessions d\'immobilisations', parentCode: '496' },
  { code: '4965', label: 'Créances sur cessions de valeurs mobilières de placement', parentCode: '496' },
  { code: '4967', label: 'Autres comptes débiteurs', parentCode: '496' },

  // Classe 5 - Comptes financiers
  { code: '50', label: 'Valeurs mobilières de placement', parentCode: '5' },
  { code: '502', label: 'Actions propres', parentCode: '50' },
  { code: '5021', label: 'Actions destinées à être attribuées aux employés et affectées à des plans déterminés', parentCode: '502' },
  { code: '5022', label: 'Actions disponibles pour être attribuées aux employés ou pour la régularisation des cours de bourse', parentCode: '502' },
  { code: '503', label: 'Actions', parentCode: '50' },
  { code: '5031', label: 'Titres cotés', parentCode: '503' },
  { code: '5035', label: 'Titres non cotés', parentCode: '503' },
  { code: '504', label: 'Autres titres conférant un droit de propriété', parentCode: '50' },
  { code: '505', label: 'Obligations et bons émis par la société et rachetés par elle', parentCode: '50' },
  { code: '506', label: 'Obligations', parentCode: '50' },
  { code: '5061', label: 'Titres cotés', parentCode: '506' },
  { code: '5065', label: 'Titres non cotés', parentCode: '506' },
  { code: '507', label: 'Bons du Trésor et bons de caisse à court terme', parentCode: '50' },
  { code: '508', label: 'Autres valeurs mobilières de placement et autres créances assimilées', parentCode: '50' },
  { code: '5081', label: 'Autres valeurs mobilières', parentCode: '508' },
  { code: '5082', label: 'Bons de souscription', parentCode: '508' },
  { code: '5088', label: 'Intérêts courus sur obligations, bons et valeurs assimilés', parentCode: '508' },
  { code: '509', label: 'Versements restant à effectuer sur valeurs mobilières de placement non libérées', parentCode: '50' },
  { code: '51', label: 'Banques, établissements financiers et assimilés', parentCode: '5' },
  { code: '511', label: 'Valeurs à l\'encaissement', parentCode: '51' },
  { code: '5111', label: 'Coupons échus à l\'encaissement', parentCode: '511' },
  { code: '5112', label: 'Chèques à encaisser', parentCode: '511' },
  { code: '5113', label: 'Effets à l\'encaissement', parentCode: '511' },
  { code: '5114', label: 'Effets à l\'escompte', parentCode: '511' },
  { code: '512', label: 'Banques', parentCode: '51' },
  { code: '5121', label: 'Comptes en euros', parentCode: '512' },
  { code: '5124', label: 'Comptes en devises', parentCode: '512' },
  { code: '517', label: 'Autres organismes financiers', parentCode: '51' },
  { code: '518', label: 'Intérêts courus', parentCode: '51' },
  { code: '5181', label: 'Intérêts courus à payer', parentCode: '518' },
  { code: '5188', label: 'Intérêts courus à recevoir', parentCode: '518' },
  { code: '519', label: 'Concours bancaires courants', parentCode: '51' },
  { code: '5191', label: 'Crédit de mobilisation de créances commerciales', parentCode: '519' },
  { code: '5193', label: 'Mobilisation de créances nées à l\'étranger', parentCode: '519' },
  { code: '5198', label: 'Intérêts courus sur concours bancaires courants', parentCode: '519' },
  { code: '52', label: 'Instruments financiers à terme et jetons', parentCode: '5' },
  { code: '521', label: 'Instruments financiers à terme', parentCode: '52' },
  { code: '522', label: 'Jetons détenus', parentCode: '52' },
  { code: '523', label: 'Jetons auto-détenus', parentCode: '52' },
  { code: '524', label: 'Jetons empruntés', parentCode: '52' },
  { code: '53', label: 'Caisse', parentCode: '5' },
  { code: '58', label: 'Virements internes', parentCode: '5' },
  { code: '59', label: 'Dépréciations des comptes financiers', parentCode: '5' },
  { code: '590', label: 'Dépréciations des valeurs mobilières de placement', parentCode: '59' },
  { code: '5903', label: 'Actions', parentCode: '590' },
  { code: '5904', label: 'Autres titres conférant un droit de propriété', parentCode: '590' },
  { code: '5906', label: 'Obligations', parentCode: '590' },
  { code: '5908', label: 'Autres valeurs mobilières de placement et créances assimilées', parentCode: '590' },

  // Classe 6 - Charges
  { code: '60', label: 'Achats', parentCode: '6' },
  { code: '601', label: 'Achats stockés - Matières premières et fournitures', parentCode: '60' },
  { code: '602', label: 'Achats stockés - Autres approvisionnements', parentCode: '60' },
  { code: '6021', label: 'Matières consommables', parentCode: '602' },
  { code: '6022', label: 'Fournitures consommables', parentCode: '602' },
  { code: '60221', label: 'Combustibles', parentCode: '6022' },
  { code: '60222', label: 'Produits d\'entretien', parentCode: '6022' },
  { code: '60223', label: 'Fournitures d\'atelier et d\'usine', parentCode: '6022' },
  { code: '60224', label: 'Fournitures de magasin', parentCode: '6022' },
  { code: '60225', label: 'Fourniture de bureau', parentCode: '6022' },
  { code: '6026', label: 'Emballages', parentCode: '602' },
  { code: '60261', label: 'Emballages perdus', parentCode: '6026' },
  { code: '60262', label: 'Malis sur emballage', parentCode: '6026' },
  { code: '60265', label: 'Emballages récupérables non identifiables', parentCode: '6026' },
  { code: '60267', label: 'Emballages à usage mixte', parentCode: '6026' },
  { code: '603', label: 'Variation des stocks d\'approvisionnements et de marchandises', parentCode: '60' },
  { code: '6031', label: 'Variation des stocks de matières premières et fournitures', parentCode: '603' },
  { code: '6032', label: 'Variation des stocks des autres approvisionnements', parentCode: '603' },
  { code: '6037', label: 'Variation des stocks de marchandises', parentCode: '603' },
  { code: '604', label: 'Achats d\'études et prestations de services', parentCode: '60' },
  { code: '605', label: 'Achats de matériel, équipements et travaux', parentCode: '60' },
  { code: '606', label: 'Achats non stockés de matière et fournitures', parentCode: '60' },
  { code: '6061', label: 'Fournitures non stockables (eau, énergie, etc.)', parentCode: '606' },
  { code: '6063', label: 'Fournitures d\'entretien et de petit équipement', parentCode: '606' },
  { code: '6064', label: 'Fournitures administratives', parentCode: '606' },
  { code: '6068', label: 'Autres matières et fournitures', parentCode: '606' },
  { code: '607', label: 'Achats de marchandises', parentCode: '60' },
  { code: '608', label: 'Compte réservé, le cas échéant, au regroupement des frais accessoires incorporés aux achats', parentCode: '60' },
  { code: '609', label: 'Rabais, remises et ristournes obtenus sur achats', parentCode: '60' },
  { code: '6098', label: 'Rabais, remises et ristournes non affectés', parentCode: '609' },
  { code: '61', label: 'Services extérieurs', parentCode: '6' },
  { code: '611', label: 'Sous-traitance générale', parentCode: '61' },
  { code: '612', label: 'Redevances de crédit-bail', parentCode: '61' },
  { code: '6122', label: 'Crédit-bail mobilier', parentCode: '612' },
  { code: '6125', label: 'Crédit-bail immobilier', parentCode: '612' },
  { code: '613', label: 'Locations', parentCode: '61' },
  { code: '6132', label: 'Locations immobilières', parentCode: '613' },
  { code: '6135', label: 'Locations mobilières', parentCode: '613' },
  { code: '614', label: 'Charges locatives et de copropriété', parentCode: '61' },
  { code: '615', label: 'Entretien et réparation', parentCode: '61' },
  { code: '6152', label: 'Entretien et réparation sur biens immobiliers', parentCode: '615' },
  { code: '6155', label: 'Entretien et réparation sur biens mobiliers', parentCode: '615' },
  { code: '6156', label: 'Maintenance', parentCode: '615' },
  { code: '616', label: 'Primes d\'assurances', parentCode: '61' },
  { code: '6161', label: 'Multirisques', parentCode: '616' },
  { code: '6162', label: 'Assurance obligatoire dommage construction', parentCode: '616' },
  { code: '6163', label: 'Assurance - transport', parentCode: '616' },
  { code: '61636', label: 'sur achats', parentCode: '6163' },
  { code: '61637', label: 'sur ventes', parentCode: '6163' },
  { code: '61638', label: 'sur autres biens', parentCode: '6163' },
  { code: '6164', label: 'Risques d\'exploitation', parentCode: '616' },
  { code: '6165', label: 'Insolvabilité clients', parentCode: '616' },
  { code: '617', label: 'Études et recherches', parentCode: '61' },
  { code: '618', label: 'Divers', parentCode: '61' },
  { code: '6181', label: 'Documentation générale', parentCode: '618' },
  { code: '6183', label: 'Documentation technique', parentCode: '618' },
  { code: '6185', label: 'Frais de colloques, séminaires, conférences', parentCode: '618' },
  { code: '619', label: 'Rabais, remises et ristournes obtenus sur services extérieurs', parentCode: '61' },
  { code: '62', label: 'Autres services extérieurs', parentCode: '6' },
  { code: '621', label: 'Personnel extérieur à l\'entité', parentCode: '62' },
  { code: '6211', label: 'Personnel intérimaire', parentCode: '621' },
  { code: '6214', label: 'Personnel détaché ou prêté à l\'entité', parentCode: '621' },
  { code: '622', label: 'Rémunérations d\'intermédiaires et honoraires', parentCode: '62' },
  { code: '6221', label: 'Commissions et courtages sur achats', parentCode: '622' },
  { code: '6222', label: 'Commissions et courtages sur ventes', parentCode: '622' },
  { code: '6224', label: 'Rémunérations des transitaires', parentCode: '622' },
  { code: '6225', label: 'Rémunérations d\'affacturage', parentCode: '622' },
  { code: '6226', label: 'Honoraires', parentCode: '622' },
  { code: '6227', label: 'Frais d\'actes et de contentieux', parentCode: '622' },
  { code: '6228', label: 'Divers', parentCode: '622' },
  { code: '623', label: 'Publicité, publications, relations publiques', parentCode: '62' },
  { code: '6231', label: 'Annonces et insertions', parentCode: '623' },
  { code: '6232', label: 'Échantillons', parentCode: '623' },
  { code: '6233', label: 'Foires et expositions', parentCode: '623' },
  { code: '6234', label: 'Cadeaux à la clientèle', parentCode: '623' },
  { code: '6235', label: 'Primes', parentCode: '623' },
  { code: '6236', label: 'Catalogues et imprimés', parentCode: '623' },
  { code: '6237', label: 'Publications', parentCode: '623' },
  { code: '6238', label: 'Divers (pourboires, dons courants)', parentCode: '623' },
  { code: '624', label: 'Transports de biens et transports collectifs du personnel', parentCode: '62' },
  { code: '6241', label: 'Transports sur achats', parentCode: '624' },
  { code: '6242', label: 'Transports sur ventes', parentCode: '624' },
  { code: '6243', label: 'Transports entre établissements ou chantiers', parentCode: '624' },
  { code: '6244', label: 'Transports administratifs', parentCode: '624' },
  { code: '6247', label: 'Transports collectifs du personnel', parentCode: '624' },
  { code: '6248', label: 'Divers', parentCode: '624' },
  { code: '625', label: 'Déplacements, missions et réceptions', parentCode: '62' },
  { code: '6251', label: 'Voyages et déplacements', parentCode: '625' },
  { code: '6255', label: 'Frais de déménagement', parentCode: '625' },
  { code: '6256', label: 'Missions', parentCode: '625' },
  { code: '6257', label: 'Réceptions', parentCode: '625' },
  { code: '626', label: 'Frais postaux et de télécommunications', parentCode: '62' },
  { code: '627', label: 'Services bancaires et assimilés', parentCode: '62' },
  { code: '6271', label: 'Frais sur titres (achat, vente, garde)', parentCode: '627' },
  { code: '6272', label: 'Commissions et frais sur émission d\'emprunts', parentCode: '627' },
  { code: '6275', label: 'Frais sur effets', parentCode: '627' },
  { code: '6276', label: 'Location de coffres', parentCode: '627' },
  { code: '6278', label: 'Autres frais et commissions sur prestations de services', parentCode: '627' },
  { code: '628', label: 'Divers', parentCode: '62' },
  { code: '6281', label: 'Concours divers (cotisations)', parentCode: '628' },
  { code: '6284', label: 'Frais de recrutement de personnel', parentCode: '628' },
  { code: '629', label: 'Rabais, remises et ristournes obtenus sur autres services extérieurs', parentCode: '62' },
  { code: '63', label: 'Impôts, taxes et versements assimilés', parentCode: '6' },
  { code: '631', label: 'Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)', parentCode: '63' },
  { code: '6311', label: 'Taxe sur les salaires', parentCode: '631' },
  { code: '6314', label: 'Cotisation pour défaut d\'investissement obligatoire dans la construction', parentCode: '631' },
  { code: '6318', label: 'Autres', parentCode: '631' },
  { code: '633', label: 'Impôts, taxes et versements assimilés sur rémunérations (autres organismes)', parentCode: '63' },
  { code: '6331', label: 'Versement de transport', parentCode: '633' },
  { code: '6332', label: 'Allocations logement', parentCode: '633' },
  { code: '6333', label: 'Contribution unique des employeurs à la formation professionnelle', parentCode: '633' },
  { code: '6334', label: 'Participation des employeurs à l\'effort de construction', parentCode: '633' },
  { code: '6335', label: 'Versements libératoires ouvrant droit à l\'exonération de la taxe d\'apprentissage', parentCode: '633' },
  { code: '6338', label: 'Autres', parentCode: '633' },
  { code: '635', label: 'Autres impôts, taxes et versements assimilés (administrations des impôts)', parentCode: '63' },
  { code: '6351', label: 'Impôts directs (sauf impôts sur les bénéfices)', parentCode: '635' },
  { code: '63511', label: 'Contribution économique territoriale', parentCode: '6351' },
  { code: '63512', label: 'Taxes foncières', parentCode: '6351' },
  { code: '63513', label: 'Autres impôts locaux', parentCode: '6351' },
  { code: '63514', label: 'Taxe sur les véhicules des sociétés', parentCode: '6351' },
  { code: '6352', label: 'Taxe sur le chiffre d\'affaires non récupérables', parentCode: '635' },
  { code: '6353', label: 'Impôts indirects', parentCode: '635' },
  { code: '6354', label: 'Droits d\'enregistrement et de timbre', parentCode: '635' },
  { code: '63541', label: 'Droits de mutation', parentCode: '6354' },
  { code: '6358', label: 'Autres droits', parentCode: '635' },
  { code: '637', label: 'Autres impôts, taxes et versements assimilés (autres organismes)', parentCode: '63' },
  { code: '6371', label: 'Contribution sociale de solidarité à la charge des sociétés', parentCode: '637' },
  { code: '6372', label: 'Taxes perçues par les organismes publics internationaux', parentCode: '637' },
  { code: '6374', label: 'Impôts et taxes exigibles à l\'étranger', parentCode: '637' },
  { code: '6378', label: 'Taxes diverses', parentCode: '637' },
  { code: '638', label: 'Rappel d\'impôts (autres qu\'impôts sur les bénéfices)', parentCode: '63' },
  { code: '64', label: 'Charges de personnel', parentCode: '6' },
  { code: '641', label: 'Rémunérations du personnel', parentCode: '64' },
  { code: '6411', label: 'Salaires, appointements', parentCode: '641' },
  { code: '6412', label: 'Congés payés', parentCode: '641' },
  { code: '6413', label: 'Primes et gratifications', parentCode: '641' },
  { code: '6414', label: 'Indemnités et avantages divers', parentCode: '641' },
  { code: '6415', label: 'Supplément familial', parentCode: '641' },
  { code: '644', label: 'Rémunération du travail de l\'exploitant', parentCode: '64' },
  { code: '645', label: 'Cotisations de sécurité sociale et de prévoyance', parentCode: '64' },
  { code: '6451', label: 'Cotisations à l\'Urssaf', parentCode: '645' },
  { code: '6452', label: 'Cotisations aux mutuelles', parentCode: '645' },
  { code: '6453', label: 'Cotisations aux caisses de retraites', parentCode: '645' },
  { code: '6454', label: 'Cotisations à Pôle emploi', parentCode: '645' },
  { code: '6458', label: 'Cotisations aux autres organismes sociaux', parentCode: '645' },
  { code: '646', label: 'Cotisations sociales personnelles de l\'exploitant', parentCode: '64' },
  { code: '647', label: 'Autres cotisations sociales', parentCode: '64' },
  { code: '6471', label: 'Prestations directes', parentCode: '647' },
  { code: '6472', label: 'Versements au comité social et économique', parentCode: '647' },
  { code: '6474', label: 'Versements aux autres œuvres sociales', parentCode: '647' },
  { code: '6475', label: 'Médecine du travail, pharmacie', parentCode: '647' },
  { code: '648', label: 'Autres charges de personnel', parentCode: '64' },
  { code: '649', label: 'Remboursements de charges de personnel', parentCode: '64' },
  { code: '65', label: 'Autres charges de gestion courante', parentCode: '6' },
  { code: '651', label: 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires', parentCode: '65' },
  { code: '6511', label: 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques', parentCode: '651' },
  { code: '6516', label: 'Droits d\'auteur et de reproduction', parentCode: '651' },
  { code: '6518', label: 'Autres droits et valeurs similaires', parentCode: '651' },
  { code: '653', label: 'Rémunérations de l\'activité des administrateurs et des gérants', parentCode: '65' },
  { code: '654', label: 'Pertes sur créances irrécouvrables', parentCode: '65' },
  { code: '6541', label: 'Créances de l\'exercice', parentCode: '654' },
  { code: '6544', label: 'Créances des exercices antérieurs', parentCode: '654' },
  { code: '655', label: 'Quote-part de résultat sur opérations faites en commun', parentCode: '65' },
  { code: '6551', label: 'Quote-part de bénéfice transférée - comptabilité du gérant', parentCode: '655' },
  { code: '6555', label: 'Quote-part de perte supportée - comptabilité des associés non gérants', parentCode: '655' },
  { code: '656', label: 'Pertes de change sur créances et dettes commerciales', parentCode: '65' },
  { code: '657', label: 'Valeurs comptables des immobilisations incorporelles et corporelles cédées', parentCode: '65' },
  { code: '658', label: 'Pénalités et autres charges', parentCode: '65' },
  { code: '6581', label: 'Pénalités sur marchés (et dédits payés sur achats et ventes)', parentCode: '658' },
  { code: '6582', label: 'Pénalités, amendes fiscales et pénales', parentCode: '658' },
  { code: '6583', label: 'Malis provenant de clauses d\'indexation', parentCode: '658' },
  { code: '6584', label: 'Lots', parentCode: '658' },
  { code: '6588', label: 'Opérations de constitution ou liquidation des fiducies', parentCode: '658' },
  { code: '66', label: 'Charges financières', parentCode: '6' },
  { code: '661', label: 'Charges d\'intérêts', parentCode: '66' },
  { code: '6611', label: 'Intérêts des emprunts et dettes', parentCode: '661' },
  { code: '66116', label: 'Intérêts des emprunts et dettes assimilées', parentCode: '6611' },
  { code: '66117', label: 'Intérêts des dettes rattachées à des participations', parentCode: '6611' },
  { code: '6612', label: 'Charges de la fiducie, résultat de la période', parentCode: '661' },
  { code: '6615', label: 'Intérêts des comptes courants et des dépôts créditeurs', parentCode: '661' },
  { code: '6616', label: 'Intérêts bancaires et sur opérations de financement (escompte...)', parentCode: '661' },
  { code: '6617', label: 'Intérêts des obligations cautionnées', parentCode: '661' },
  { code: '6618', label: 'Intérêts des autres dettes', parentCode: '661' },
  { code: '66181', label: 'Intérêts des dettes commerciales', parentCode: '6618' },
  { code: '66188', label: 'Intérêts des dettes diverses', parentCode: '6618' },
  { code: '664', label: 'Pertes sur créances liées à des participations', parentCode: '66' },
  { code: '665', label: 'Escomptes accordés', parentCode: '66' },
  { code: '666', label: 'Pertes de change financières', parentCode: '66' },
  { code: '667', label: 'Charges sur cession d\'éléments financiers', parentCode: '66' },
  { code: '6671', label: 'Valeurs comptables des immobilisations financières cédées', parentCode: '667' },
  { code: '6672', label: 'Charges nettes sur cessions de titres immobilisés de l\'activité de portefeuille', parentCode: '667' },
  { code: '6673', label: 'Charges nettes sur cessions de valeurs mobilières de placement', parentCode: '667' },
  { code: '6674', label: 'Charges nettes sur cessions de jetons', parentCode: '667' },
  { code: '668', label: 'Autres charges financières', parentCode: '66' },
  { code: '6683', label: 'Mali provenant du rachat par l\'entité d\'actions et obligations émises par elle-même', parentCode: '668' },
  { code: '67', label: 'Charges exceptionnelles', parentCode: '6' },
  { code: '672', label: 'Compte à la disposition des entités pour enregistrer, en cours d\'exercice, les charges sur exercices antérieurs', parentCode: '67' },
  { code: '678', label: 'Autres charges exceptionnelles', parentCode: '67' },
  { code: '68', label: 'Dotations aux amortissements, aux dépréciations et aux provisions', parentCode: '6' },
  { code: '681', label: 'Dotations aux amortissements, aux dépréciations et aux provisions (à inscrire dans les charges d\'exploitation)', parentCode: '68' },
  { code: '6811', label: 'Dotations aux amortissements sur immobilisations incorporelles et corporelles', parentCode: '681' },
  { code: '68111', label: 'Immobilisations incorporelles et frais d\'établissement', parentCode: '6811' },
  { code: '68112', label: 'Immobilisations corporelles', parentCode: '6811' },
  { code: '6815', label: 'Dotations aux provisions d\'exploitation', parentCode: '681' },
  { code: '6816', label: 'Dotations pour dépréciations des immobilisations incorporelles et corporelles', parentCode: '681' },
  { code: '68161', label: 'Immobilisations incorporelles', parentCode: '6816' },
  { code: '68162', label: 'Immobilisations corporelles', parentCode: '6816' },
  { code: '6817', label: 'Dotations pour dépréciations des actifs circulants', parentCode: '681' },
  { code: '68173', label: 'Stocks et en-cours', parentCode: '6817' },
  { code: '68174', label: 'Créances', parentCode: '6817' },
  { code: '686', label: 'Dotations aux amortissements, aux dépréciations et aux provisions (à inscrire dans les charges financières)', parentCode: '68' },
  { code: '6861', label: 'Dotations aux amortissements des primes de remboursement des emprunts', parentCode: '686' },
  { code: '6862', label: 'Dotations aux amortissements des frais d\'émission des emprunts', parentCode: '686' },
  { code: '6865', label: 'Dotations aux provisions financières', parentCode: '686' },
  { code: '6866', label: 'Dotations pour dépréciation des éléments financiers', parentCode: '686' },
  { code: '68662', label: 'Immobilisations financières', parentCode: '6866' },
  { code: '68665', label: 'Valeurs mobilières de placement', parentCode: '6866' },
  { code: '687', label: 'Dotations aux amortissements, aux dépréciations et aux provisions (à inscrire dans les charges exceptionnelles)', parentCode: '68' },
  { code: '6871', label: 'Dotations aux amortissements exceptionnels des immobilisations', parentCode: '687' },
  { code: '6872', label: 'Dotations aux provisions réglementées (immobilisations)', parentCode: '687' },
  { code: '68725', label: 'Amortissements dérogatoires', parentCode: '6872' },
  { code: '6873', label: 'Dotations aux provisions réglementées (stocks)', parentCode: '687' },
  { code: '6874', label: 'Dotations aux autres provisions réglementées', parentCode: '687' },
  { code: '6875', label: 'Dotations aux provisions exceptionnelles', parentCode: '687' },
  { code: '6876', label: 'Dotations pour dépréciations exceptionnelles', parentCode: '687' },
  { code: '69', label: 'Impôts sur les bénéfices', parentCode: '6' },
  { code: '691', label: 'Participation des salariés aux résultats', parentCode: '69' },
  { code: '695', label: 'Impôts sur les bénéfices', parentCode: '69' },
  { code: '6951', label: 'Impôts dus en France', parentCode: '695' },
  { code: '6952', label: 'Contribution additionnelle à l\'impôt sur les bénéfices', parentCode: '695' },
  { code: '6954', label: 'Impôts dus à l\'étranger', parentCode: '695' },
  { code: '696', label: 'Suppléments d\'impôt sur les sociétés liés aux distributions', parentCode: '69' },
  { code: '698', label: 'Intégration fiscale', parentCode: '69' },
  { code: '6981', label: 'Intégration fiscale - Charges', parentCode: '698' },
  { code: '6989', label: 'Intégration fiscale - Produits', parentCode: '698' },
  { code: '699', label: 'Produits - Reports en arrière des déficits', parentCode: '69' },

  // Classe 7 - Produits
  // No 79: the transferts de charges (791, 796, 797) were removed by règlement
  // ANC n° 2022-06 (fiscal years opened from 1 January 2025). Charts of
  // earlier years keep theirs; reports still read 79 for those years.
  { code: '70', label: 'Ventes', parentCode: '7' },
  { code: '701', label: 'Ventes de produits finis', parentCode: '70' },
  { code: '702', label: 'Ventes de produits intermédiaires', parentCode: '70' },
  { code: '703', label: 'Ventes de produits résiduels', parentCode: '70' },
  { code: '704', label: 'Travaux', parentCode: '70' },
  { code: '705', label: 'Études', parentCode: '70' },
  { code: '706', label: 'Prestations de services', parentCode: '70' },
  { code: '707', label: 'Ventes de marchandises', parentCode: '70' },
  { code: '708', label: 'Produits des activités annexes', parentCode: '70' },
  { code: '7081', label: 'Produits des services exploités dans l\'intérêt du personnel', parentCode: '708' },
  { code: '7082', label: 'Commissions et courtages', parentCode: '708' },
  { code: '7083', label: 'Locations diverses', parentCode: '708' },
  { code: '7084', label: 'Mise à disposition de personnel facturée', parentCode: '708' },
  { code: '7085', label: 'Ports et frais accessoires facturés', parentCode: '708' },
  { code: '7086', label: 'Bonis sur reprises d\'emballages consignés', parentCode: '708' },
  { code: '7087', label: 'Bonifications obtenues des clients et primes sur ventes', parentCode: '708' },
  { code: '7088', label: 'Autres produits d\'activités annexes (cessions d\'approvisionnements)', parentCode: '708' },
  { code: '709', label: 'Rabais, remises et ristournes accordés', parentCode: '70' },
  { code: '7091', label: 'Rabais, remises et ristournes accordés sur ventes de produits finis', parentCode: '709' },
  { code: '7092', label: 'Rabais, remises et ristournes accordés sur ventes de produits intermédiaires', parentCode: '709' },
  { code: '7094', label: 'Rabais, remises et ristournes accordés sur travaux', parentCode: '709' },
  { code: '7095', label: 'Rabais, remises et ristournes accordés sur études', parentCode: '709' },
  { code: '7096', label: 'Rabais, remises et ristournes accordés sur prestations de services', parentCode: '709' },
  { code: '7097', label: 'Rabais, remises et ristournes accordés sur ventes de marchandises', parentCode: '709' },
  { code: '7098', label: 'Rabais, remises et ristournes accordés sur produits des activités annexes', parentCode: '709' },
  { code: '71', label: 'Production stockée', parentCode: '7' },
  { code: '713', label: 'Variation des stocks des en-cours de production et de produits', parentCode: '71' },
  { code: '7133', label: 'Variation des en-cours de production de biens', parentCode: '713' },
  { code: '71331', label: 'Produits en cours', parentCode: '7133' },
  { code: '71335', label: 'Travaux en cours', parentCode: '7133' },
  { code: '7134', label: 'Variation des en-cours de production de services', parentCode: '713' },
  { code: '71341', label: 'Études en cours', parentCode: '7134' },
  { code: '71345', label: 'Prestations de services en cours', parentCode: '7134' },
  { code: '7135', label: 'Variation des stocks de produits', parentCode: '713' },
  { code: '71351', label: 'Produits intermédiaires', parentCode: '7135' },
  { code: '71355', label: 'Produits finis', parentCode: '7135' },
  { code: '71358', label: 'Produits résiduels', parentCode: '7135' },
  { code: '72', label: 'Production immobilisée', parentCode: '7' },
  { code: '721', label: 'Immobilisations incorporelles', parentCode: '72' },
  { code: '722', label: 'Immobilisations corporelles', parentCode: '72' },
  { code: '74', label: 'Subventions', parentCode: '7' },
  { code: '741', label: 'Subventions d\'exploitation', parentCode: '74' },
  { code: '742', label: 'Subventions d\'équilibre', parentCode: '74' },
  { code: '747', label: 'Quote-part des subventions d\'investissement virée au résultat de l\'exercice', parentCode: '74' },
  { code: '75', label: 'Autres produits de gestion courante', parentCode: '7' },
  { code: '751', label: 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques, droits et valeurs similaires', parentCode: '75' },
  { code: '7511', label: 'Redevances pour concessions, brevets, licences, marques, procédés, solutions informatiques', parentCode: '751' },
  { code: '7516', label: 'Droits d\'auteur et de reproduction', parentCode: '751' },
  { code: '7518', label: 'Autres droits et valeurs similaires', parentCode: '751' },
  { code: '752', label: 'Revenus des immeubles non affectés à des activités professionnelles', parentCode: '75' },
  { code: '753', label: 'Rémunérations de l\'activité des administrateurs et des gérants', parentCode: '75' },
  { code: '754', label: 'Ristournes perçues des coopératives provenant des excédents', parentCode: '75' },
  { code: '755', label: 'Quote-part de résultat sur opérations faites en commun', parentCode: '75' },
  { code: '7551', label: 'Quote-part de perte transférée - comptabilité du gérant', parentCode: '755' },
  { code: '7555', label: 'Quote-part de bénéfice attribuée - comptabilité des associés non-gérants', parentCode: '755' },
  { code: '756', label: 'Gains de change sur créances et dettes commerciales', parentCode: '75' },
  { code: '757', label: 'Produits des cessions d\'immobilisations incorporelles et corporelles', parentCode: '75' },
  { code: '758', label: 'Indemnités et autres produits', parentCode: '75' },
  { code: '7581', label: 'Dédits et pénalités perçus sur achats et ventes', parentCode: '758' },
  { code: '7582', label: 'Libéralités reçues', parentCode: '758' },
  { code: '7583', label: 'Rentrées sur créances amorties', parentCode: '758' },
  { code: '7584', label: 'Dégrèvements d\'impôts autres qu\'impôts sur les bénéfices', parentCode: '758' },
  { code: '7585', label: 'Bonis provenant de clauses d\'indexation', parentCode: '758' },
  { code: '7586', label: 'Lots', parentCode: '758' },
  { code: '7587', label: 'Indemnités d\'assurance', parentCode: '758' },
  { code: '7588', label: 'Opérations de constitution ou liquidation des fiducies', parentCode: '758' },
  { code: '76', label: 'Produits financiers', parentCode: '7' },
  { code: '761', label: 'Produits de participations', parentCode: '76' },
  { code: '7611', label: 'Revenus des titres de participation', parentCode: '761' },
  { code: '7612', label: 'Produits de la fiducie, résultat de la période', parentCode: '761' },
  { code: '7616', label: 'Revenus sur autres formes de participation', parentCode: '761' },
  { code: '7617', label: 'Revenus des créances rattachées à des participations', parentCode: '761' },
  { code: '762', label: 'Produits des autres immobilisations financières', parentCode: '76' },
  { code: '7621', label: 'Revenus des titres immobilisés autres que les titres immobilisés de l\'activité de portefeuille (droit de propriété)', parentCode: '762' },
  { code: '7626', label: 'Revenus des prêts', parentCode: '762' },
  { code: '7627', label: 'Revenus des créances immobilisées', parentCode: '762' },
  { code: '763', label: 'Revenus des autres créances', parentCode: '76' },
  { code: '7631', label: 'Revenus des créances commerciales', parentCode: '763' },
  { code: '7638', label: 'Revenus des créances diverses', parentCode: '763' },
  { code: '764', label: 'Revenus des valeurs mobilières de placement', parentCode: '76' },
  { code: '765', label: 'Escomptes obtenus', parentCode: '76' },
  { code: '766', label: 'Gains de change financiers', parentCode: '76' },
  { code: '767', label: 'Produits sur cession d\'éléments financiers', parentCode: '76' },
  { code: '7671', label: 'Produits des cessions d\'immobilisations financières', parentCode: '767' },
  { code: '7672', label: 'Produits nets sur cessions de titres immobilisés de l\'activité de portefeuille', parentCode: '767' },
  { code: '7673', label: 'Produits nets sur cessions de valeurs mobilières de placement', parentCode: '767' },
  { code: '7674', label: 'Produits nets sur cessions de jetons', parentCode: '767' },
  { code: '768', label: 'Autres produits financiers', parentCode: '76' },
  { code: '7683', label: 'Bonis provenant du rachat par l\'entité d\'actions et obligations émises par elle-même', parentCode: '768' },
  { code: '77', label: 'Produits exceptionnels', parentCode: '7' },
  { code: '772', label: 'Compte à la disposition des entités pour enregistrer, en cours d\'exercice, les produits sur exercices antérieurs', parentCode: '77' },
  { code: '778', label: 'Autres produits exceptionnels', parentCode: '77' },
  { code: '78', label: 'Reprises sur amortissements, dépréciations et provisions', parentCode: '7' },
  { code: '781', label: 'Reprises sur amortissements, dépréciations et provisions (à inscrire dans les produits d\'exploitation)', parentCode: '78' },
  { code: '7811', label: 'Reprises sur amortissements des immobilisations incorporelles et corporelles', parentCode: '781' },
  { code: '78111', label: 'Immobilisations incorporelles et frais d\'établissement', parentCode: '7811' },
  { code: '78112', label: 'Immobilisations corporelles', parentCode: '7811' },
  { code: '7815', label: 'Reprises sur provisions d\'exploitation', parentCode: '781' },
  { code: '7816', label: 'Reprises sur dépréciations des immobilisations incorporelles et corporelles', parentCode: '781' },
  { code: '78161', label: 'Immobilisations incorporelles', parentCode: '7816' },
  { code: '78162', label: 'Immobilisations corporelles', parentCode: '7816' },
  { code: '7817', label: 'Reprises sur dépréciations des actifs circulants', parentCode: '781' },
  { code: '78173', label: 'Stocks et en-cours', parentCode: '7817' },
  { code: '78174', label: 'Créances', parentCode: '7817' },
  { code: '786', label: 'Reprises sur dépréciations et provisions (à inscrire dans les produits financiers)', parentCode: '78' },
  { code: '7865', label: 'Reprises sur provisions financières', parentCode: '786' },
  { code: '7866', label: 'Reprises sur dépréciations des éléments financiers', parentCode: '786' },
  { code: '78662', label: 'Immobilisations financières', parentCode: '7866' },
  { code: '78665', label: 'Valeurs mobilières de placement', parentCode: '7866' },
  { code: '787', label: 'Reprises sur dépréciations et provisions (à inscrire dans les produits exceptionnels)', parentCode: '78' },
  { code: '7872', label: 'Reprises sur provisions réglementées (immobilisations)', parentCode: '787' },
  { code: '78725', label: 'Amortissements dérogatoires', parentCode: '7872' },
  { code: '7873', label: 'Reprises sur provisions réglementées (stocks)', parentCode: '787' },
  { code: '7874', label: 'Reprises sur autres provisions réglementées', parentCode: '787' },
  { code: '7875', label: 'Reprises sur provisions exceptionnelles', parentCode: '787' },
  { code: '7876', label: 'Reprises sur dépréciations exceptionnelles', parentCode: '787' },

  // Classe 8 - Comptes spéciaux
  { code: '8', label: 'Comptes spéciaux' },
  { code: '80', label: 'Engagements hors bilan', parentCode: '8' },
  { code: '801', label: 'Engagements donnés par l\'entité', parentCode: '80' },
  { code: '8011', label: 'Avals, cautions, garanties', parentCode: '801' },
  { code: '8014', label: 'Effets circulant sous l\'endos de l\'entité', parentCode: '801' },
  { code: '8016', label: 'Redevances crédit-bail restant à courir', parentCode: '801' },
  { code: '80161', label: 'Crédit-bail mobilier', parentCode: '8016' },
  { code: '80165', label: 'Crédit-bail immobilier', parentCode: '8016' },
  { code: '8018', label: 'Autres engagements donnés', parentCode: '801' },
  { code: '802', label: 'Engagements reçus par l\'entité', parentCode: '80' },
  { code: '8021', label: 'Avals, cautions, garanties reçues', parentCode: '802' },
  { code: '8024', label: 'Créances escomptées non échues', parentCode: '802' },
  { code: '8026', label: 'Engagements reçus pour utilisation en crédit-bail', parentCode: '802' },
  { code: '80261', label: 'Crédit-bail mobilier reçu', parentCode: '8026' },
  { code: '80265', label: 'Crédit-bail immobilier reçu', parentCode: '8026' },
  { code: '8028', label: 'Autres engagements reçus', parentCode: '802' },
  { code: '809', label: 'Contrepartie des engagements', parentCode: '80' },
  { code: '8091', label: 'Contrepartie de 801 (engagements donnés)', parentCode: '809' },
  { code: '8092', label: 'Contrepartie de 802 (engagements reçus)', parentCode: '809' },
  { code: '81', label: 'Immobilisations en non-valeurs', parentCode: '8' },
  { code: '88', label: 'Résultats en instance d\'affectation', parentCode: '8' },
  { code: '89', label: 'Bilan', parentCode: '8' },
  { code: '890', label: 'Bilan d\'ouverture', parentCode: '89' },
  { code: '891', label: 'Bilan de clôture', parentCode: '89' },
]

/**
 * Detailed accounts (more than 4 digits) that Kledg posts to itself, so every
 * chart has them even without the optional accounts: deductible VAT on fixed
 * assets and on other goods and services, collected VAT (invoices and expense
 * reports, lib/invoices/posting-plan.ts, lib/expense-reports).
 */
export const KLEDG_POSTING_ACCOUNTS: readonly string[] = ['44562', '44566', '44571']

/** Class 8 and accounts of more than 4 digits are optional in a chart, except KLEDG_POSTING_ACCOUNTS. */
export function isOptionalPcgAccount(code: string): boolean {
  if (KLEDG_POSTING_ACCOUNTS.includes(code)) return false
  return code.startsWith('8') || code.length > 4
}
