/**
 * The MCP tools that closed the last parity gaps (lib/mcp/route-coverage.ts):
 * file exports, Qonto statements and documents, the SIREN lookup and the
 * company lifecycle. Against PostgreSQL, called through the real /api/mcp
 * handler with API keys of each level (session mocked; Better Auth,
 * services, row level security and audit log real), with Qonto and the
 * company directory answered by a stubbed fetch (no network):
 * - each tool exists at its level and above, never below;
 * - a company outside the key's grant, or of which the user is not a
 *   member, is "Société introuvable"; an object of another company
 *   (fiscal year, receipt, invoice) is "introuvable";
 * - a viewer cannot export (reports:export) nor use a full control tool;
 * - files come back as an embedded resource (base64 blob, MIME type, file
 *   name) generated by the route's service, never with a URL;
 * - company creation follows the instance policy (and its hook), needs a
 *   grant of every company, and follows the execution mode (approval in
 *   Kledg with a pending action without company);
 * - archiving makes a company read-only and hides it, restoring reverses it,
 *   for instance administrators only.
 *
 * Run with KLEDG_RLS=enforce too (docs/rls.md). Skipped when the test
 * database server is unreachable.
 */

import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest'

type Actor = { id: string; email: string; role: string | null }

const state = await vi.hoisted(async () => {
  const { useTestDatabase } = await import('@/lib/__tests__/helpers/test-db')
  useTestDatabase('mcp_files')
  process.env.BETTER_AUTH_SECRET ??= 'kledg-test-secret-0123456789abcdef0123456789'
  process.env.BETTER_AUTH_URL = 'http://localhost:3000'
  process.env.NEXT_PUBLIC_APP_URL = 'http://localhost:3000'
  process.env.RATE_LIMIT_DISABLED = 'true'
  process.env.ENCRYPTION_KEY ??= 'a'.repeat(64)
  return {
    user: null as null | { id: string; email: string; name: string | null; role: string | null },
    /** A fork's company creation policy (null: Kledg's, instance administrators only). */
    creationRefusal: null as null | ((actor: Actor) => Promise<{ message: string; link?: string } | null>),
    afterCreated: null as null | ((companyId: string, actor: Actor) => Promise<void>),
  }
})

vi.mock('@/lib/session', () => ({ getCurrentUser: async () => state.user }))
vi.mock('@/lib/instance/policy', async (importOriginal) => {
  const original = await importOriginal<typeof import('@/lib/instance/policy')>()
  return {
    ...original,
    companyCreationRefusal: (actor: Actor) => (state.creationRefusal ? state.creationRefusal(actor) : original.companyCreationRefusal(actor)),
    afterCompanyCreated: (companyId: string, actor: Actor) => (state.afterCreated ? state.afterCreated(companyId, actor) : original.afterCompanyCreated(companyId, actor)),
  }
})
// File downloads go through the public-address fetch (node:https); here they
// reach the stubbed global fetch. The address guard has its own tests.
vi.mock('@/lib/integrations/public-https-fetch', () => ({
  publicFetch: (...args: Parameters<typeof fetch>) => fetch(...args),
}))

import { prepareTestDatabase, testDatabaseAvailable } from '@/lib/__tests__/helpers/test-db'
import type { AccessLevel, CompanyAccess, ExecutionMode } from '@/lib/ai-access/access'

const available = await testDatabaseAvailable()

type Handler = (request: Request) => Promise<Response>

let prisma: typeof import('@/lib/prisma').prisma
let mcp: Record<'POST', Handler>
let createApiKeyWithGrant: typeof import('@/lib/ai-access/create-api-key.service').createApiKeyWithGrant

const OWNER = { id: 'u-owner', email: 'owner@test.local', name: 'Owner', role: 'user' }
const VIEWER = { id: 'u-viewer', email: 'viewer@test.local', name: 'Viewer', role: 'user' }
const ADMIN = { id: 'u-admin', email: 'admin@test.local', name: 'Admin', role: 'admin' }

const LEVEL: Record<string, AccessLevel> = {
  export_report: 'read',
  get_qonto_statements: 'read',
  list_qonto_receipts: 'read',
  get_file: 'read',
  lookup_siren: 'read',
  create_company: 'admin',
  archive_company: 'admin',
  restore_company: 'admin',
}

const STATEMENT_ID = '7c1f0a52-2b3d-4c5e-8f60-71a2b3c4d5e6'
const TX_UUID = '0b7f1d64-5a8c-4b6e-9a51-3f1c2d3e4f50'
const PDF_BYTES = Buffer.from('%PDF-1.4 relevé de test')
const RECEIPT_BYTES = Buffer.from('%PDF-1.4 justificatif')
const INVOICE_BYTES = Buffer.from('%PDF-1.4 facture')

/** Arguments of each company tool (ids need not exist: access is checked first). */
const COMPANY_ARGS: Record<string, Record<string, unknown>> = {
  export_report: { report: 'journal_excel' },
  get_qonto_statements: {},
  list_qonto_receipts: { transactionId: TX_UUID },
  get_file: { source: 'qonto_statement', statementId: STATEMENT_ID },
  archive_company: {},
  restore_company: {},
}

const NEW_COMPANY = {
  name: 'Nouvelle SAS',
  siren: '552100554',
  legalType: 'SAS',
  firstFiscalYear: { startDate: '2026-01-01', endDate: '2026-12-31', isFirst: false },
  vatRegime: 'normal',
  corporateTaxRegime: 'simplified',
  totalShares: 100,
  shareNominalValue: 10.5,
  shareholders: [{ type: 'PHYSICAL', firstName: 'Jeanne', name: 'Martin', numberOfShares: 100 }],
}

const ids = {} as Record<string, string>
const day = (iso: string) => new Date(`${iso}T00:00:00.000Z`)

async function seedCompany(prefix: 'a' | 'b' | 'c', siren: string, members: Array<[string, string]>) {
  const company = await prisma.company.create({
    data: { name: `Société ${prefix.toUpperCase()}`, slug: `societe-${prefix}`, siren, legalType: 'SAS', closingDay: 31, closingMonth: 12, vatRegime: 'normal', corporateTaxRegime: 'simplified' },
  })
  await prisma.organization.create({ data: { id: `org-${prefix}`, name: company.name, slug: `org-${prefix}`, createdAt: new Date(), companyId: company.id } })
  for (const [userId, role] of members) {
    await prisma.member.create({ data: { id: `m-${prefix}-${userId}`, userId, organizationId: `org-${prefix}`, role, createdAt: new Date() } })
  }
  const fy = await prisma.fiscalYear.create({
    data: { companyId: company.id, year: 2025, startDate: day('2025-01-01'), endDate: day('2025-12-31'), closingDay: 31, closingMonth: 12 },
  })
  for (const [code, label] of [
    ['101', 'Capital'],
    ['512000', 'Banque'],
    ['606100', 'Fournitures non stockables'],
    ['706000', 'Prestations de services'],
  ]) {
    const account = await prisma.account.create({ data: { companyId: company.id, fiscalYearId: fy.id, code, label, isPCG: true } })
    ids[`${prefix}:${code}`] = account.id
  }
  for (const code of ['BQ', 'OD', 'AC', 'VE', 'AN']) await prisma.journal.create({ data: { companyId: company.id, code, label: code } })
  ids[`${prefix}Company`] = company.id
  ids[`${prefix}Fy`] = fy.id
}

async function seed() {
  await prepareTestDatabase('mcp_files')
  for (const user of [OWNER, VIEWER, ADMIN]) await prisma.user.create({ data: { id: user.id, email: user.email, name: user.name, role: user.role } })
  await seedCompany('a', '123456782', [
    [OWNER.id, 'companyAdmin'],
    [VIEWER.id, 'viewer'],
  ])
  await seedCompany('b', '222222222', [[OWNER.id, 'companyAdmin']])
  await seedCompany('c', '333333333', [])

  // A validated entry of company A, for the exports.
  const { createEntry } = await import('@/lib/accounting/services/entry-lifecycle.service')
  const journal = await prisma.journal.findFirstOrThrow({ where: { companyId: ids.aCompany, code: 'OD' } })
  await createEntry({
    companyId: ids.aCompany,
    journalId: journal.id,
    date: '2025-03-10',
    description: 'Fournitures',
    status: 'validated',
    lines: [
      { accountId: ids['a:606100'], debit: '120', credit: 0 },
      { accountId: ids['a:512000'], debit: 0, credit: '120' },
    ],
  })

  // Qonto connected for A only, a receipt of A and one of B, a Qonto invoice of A and one of B.
  const { encrypt } = await import('@/lib/integrations/encryption')
  await prisma.bankConnection.create({ data: { companyId: ids.aCompany, provider: 'QONTO', login: 'qonto-login', secretKeyEncrypted: encrypt('qonto-secret', process.env.ENCRYPTION_KEY!) } })
  for (const prefix of ['a', 'b'] as const) {
    const attachment = await prisma.attachment.create({
      data: { companyId: ids[`${prefix}Company`], externalAttachmentId: `att-${prefix}`, transactionUuid: TX_UUID, fileName: `recu-${prefix}.pdf`, fileContentType: 'application/pdf' },
    })
    ids[`${prefix}Attachment`] = attachment.id
    const tiers = await prisma.tiers.create({ data: { companyId: ids[`${prefix}Company`], kind: 'SUPPLIER', name: 'Papeterie Durand', auxiliaryAccountNumber: 'F00001' } })
    const invoice = await prisma.invoice.create({
      data: {
        companyId: ids[`${prefix}Company`],
        direction: 'PURCHASE',
        tiersId: tiers.id,
        number: `F-${prefix}`,
        issueDate: day('2025-03-01'),
        dueDate: day('2025-03-31'),
        totalExclTax: 100,
        totalVat: 20,
        totalInclTax: 120,
        source: 'QONTO',
        externalId: `si-${prefix}`,
        externalAttachmentId: 'att-inv',
      },
    })
    ids[`${prefix}Invoice`] = invoice.id
  }
}

async function apiKey(
  level: AccessLevel,
  { access = { allCompanies: true, companyIds: [] }, user = OWNER, mode = 'automatic' }: { access?: CompanyAccess; user?: typeof OWNER; mode?: ExecutionMode } = {},
): Promise<string> {
  return (await createApiKeyWithGrant({ ...user }, `Clé ${level} ${mode}`, access, level, mode)).key
}

type Content = { type: string; text?: string; resource?: { uri: string; mimeType: string; blob: string; _meta?: { fileName: string; size: number } } }

async function rpc(key: string, method: string, params: unknown = {}) {
  const response = await mcp.POST(
    new Request('http://localhost:3000/api/mcp', {
      method: 'POST',
      headers: { 'x-api-key': key, 'content-type': 'application/json', accept: 'application/json, text/event-stream' },
      body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }),
    }),
  )
  expect(response.status).toBe(200)
  const text = await response.text()
  const raw = text.trim().startsWith('{') ? text : (text.split('\n').find((l) => l.startsWith('data: '))?.slice(6) ?? 'null')
  return JSON.parse(raw) as { result?: { tools?: Array<{ name: string }>; content?: Content[]; isError?: boolean }; error?: { message: string } }
}

const toolNames = async (key: string) => ((await rpc(key, 'tools/list')).result?.tools ?? []).map((t) => t.name)

interface CallResult {
  ok: boolean
  text: string
  data: Record<string, any> // eslint-disable-line @typescript-eslint/no-explicit-any
  content: Content[]
}

async function call(key: string, name: string, args: Record<string, unknown>): Promise<CallResult> {
  const body = await rpc(key, 'tools/call', { name, arguments: args })
  const text = body.result?.content?.[0]?.text ?? body.error?.message ?? ''
  const ok = !body.result?.isError && !body.error
  return { ok, text, data: ok ? JSON.parse(text) : {}, content: body.result?.content ?? [] }
}

async function ok(key: string, name: string, args: Record<string, unknown>) {
  const result = await call(key, name, args)
  expect(result.ok, `${name}: ${result.text}`).toBe(true)
  return result
}

/** The embedded file of a result: its resource and its bytes. */
function fileOf(result: CallResult) {
  const block = result.content.find((c) => c.type === 'resource')
  expect(block?.resource, result.text).toBeDefined()
  const resource = block!.resource!
  return { resource, bytes: Buffer.from(resource.blob, 'base64') }
}

async function approve(actionId: string) {
  const { decideAction } = await import('@/lib/mcp/full-control/pending-actions')
  const row = await prisma.mcpPendingAction.findUniqueOrThrow({ where: { id: actionId } })
  return decideAction(row.userId, actionId, 'approve')
}

/** Qonto API, Qonto file hosts and the company directory, by URL; every URL is recorded. */
const fetched: string[] = []
function stubNetwork() {
  const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } })
  const statement = { id: STATEMENT_ID, bank_account_id: 'acc-1', period: '08-2025', file: { file_name: 'releve-aout.pdf', file_content_type: 'application/pdf', file_size: String(PDF_BYTES.length), file_url: 'https://files.qonto.com/s/aout.pdf' } }
  vi.stubGlobal(
    'fetch',
    vi.fn(async (input: string | URL | Request) => {
      const url = new URL(input instanceof Request ? input.url : String(input))
      fetched.push(url.toString())
      if (url.hostname === 'files.qonto.com') {
        const bytes = url.pathname.endsWith('aout.pdf') ? PDF_BYTES : url.pathname.includes('facture') ? INVOICE_BYTES : RECEIPT_BYTES
        return new Response(new Uint8Array(bytes), { status: 200, headers: { 'content-type': 'application/pdf', 'content-length': String(bytes.length) } })
      }
      if (url.hostname === 'recherche-entreprises.api.gouv.fr') {
        return json({ results: [{ siren: '552100554', nom_raison_sociale: 'NOUVELLE SAS', nature_juridique: '5710', activite_principale: '62.01Z', date_creation: '2020-02-01', etat_administratif: 'A', siege: { siret: '55210055400013', numero_voie: '1', type_voie: 'RUE', libelle_voie: 'DE RIVOLI', code_postal: '75001', libelle_commune: 'PARIS' } }] })
      }
      if (url.pathname.endsWith(`/statements/${STATEMENT_ID}`)) return json({ statement })
      if (url.pathname.endsWith('/statements')) return json({ statements: [statement], meta: { current_page: 1, next_page: null, prev_page: null, total_pages: 1, total_count: 1, per_page: 100 } })
      if (url.pathname.endsWith(`/transactions/${TX_UUID}/attachments`)) {
        return json({ attachments: ['a', 'b'].map((p) => ({ id: `att-${p}`, created_at: '2025-03-10T10:00:00Z', file_name: `recu-${p}.pdf`, file_size: '20', file_content_type: 'application/pdf', url: `https://files.qonto.com/r/recu-${p}.pdf` })) })
      }
      if (url.pathname.endsWith('/attachments/att-inv')) return json({ attachment: { id: 'att-inv', file_name: 'facture.pdf', file_content_type: 'application/pdf', url: 'https://files.qonto.com/f/facture.pdf' } })
      return json({ errors: [{ detail: 'not found' }] }, 404)
    }),
  )
}

describe.skipIf(!available)('MCP tools for files and the company lifecycle', () => {
  beforeAll(async () => {
    await prepareTestDatabase('mcp_files')
    ;({ prisma } = await import('@/lib/prisma'))
    mcp = (await import('@/app/api/mcp/route')) as unknown as Record<'POST', Handler>
    ;({ createApiKeyWithGrant } = await import('@/lib/ai-access/create-api-key.service'))
  }, 60_000)

  beforeEach(async () => {
    state.creationRefusal = null
    state.afterCreated = null
    fetched.length = 0
    stubNetwork()
    await seed()
  })

  afterEach(() => {
    vi.unstubAllGlobals()
  })

  afterAll(async () => {
    await prisma?.$disconnect()
  })

  describe('access', () => {
    it('lists each tool at its level and above, never below', async () => {
      const names = { read: await toolNames(await apiKey('read')), write: await toolNames(await apiKey('write')), admin: await toolNames(await apiKey('admin')) }
      const rank = { read: 0, write: 1, admin: 2 }
      for (const [tool, level] of Object.entries(LEVEL)) {
        for (const key of ['read', 'write', 'admin'] as const) {
          expect(names[key].includes(tool), `${tool} with a ${key} key`).toBe(rank[key] >= rank[level])
        }
      }
    })

    it('answers "Société introuvable" for a company outside the grant or of which the user is not a member', async () => {
      const onlyA = await apiKey('admin', { access: { allCompanies: false, companyIds: [ids.aCompany] } })
      for (const [tool, args] of Object.entries(COMPANY_ARGS)) {
        for (const companyId of [ids.bCompany, ids.cCompany]) {
          const result = await call(onlyA, tool, { companyId, ...args })
          expect(result.ok, `${tool} ${companyId}`).toBe(false)
          expect(result.text, tool).toBe('Société introuvable')
        }
      }
      // An instance administrator limited to company A does not reach B either.
      const adminOnlyA = await apiKey('admin', { user: ADMIN, access: { allCompanies: false, companyIds: [ids.aCompany] } })
      expect((await call(adminOnlyA, 'archive_company', { companyId: ids.bCompany })).text).toBe('Société introuvable')
      expect(await prisma.company.count({ where: { archivedAt: { not: null } } })).toBe(0)
    })

    it('refuses a viewer the exports (reports:export) and the full control tools, and lets it read documents', async () => {
      const viewer = await apiKey('admin', { user: VIEWER })
      const exported = await call(viewer, 'export_report', { companyId: ids.aCompany, report: 'journal_excel' })
      expect(exported.text).toMatch(/^Action non autorisée : votre rôle \(Lecture seule\)/)
      for (const tool of ['archive_company', 'restore_company']) {
        const result = await call(viewer, tool, { companyId: ids.aCompany })
        expect(result.ok, tool).toBe(false)
        expect(result.text, tool).toBe("Action réservée aux administrateurs de l'instance.")
      }
      const created = await call(viewer, 'create_company', NEW_COMPANY)
      expect(created.text).toBe("La création de sociétés est réservée aux administrateurs de l'instance.")
      const statements = await call(viewer, 'get_qonto_statements', { companyId: ids.aCompany })
      expect(statements.ok, statements.text).toBe(true)
    })
  })

  describe('export_report', () => {
    it('returns the file of the route as an embedded resource, for several reports', async () => {
      const key = await apiKey('read')
      const cases: Array<[Record<string, unknown>, string, string]> = [
        [{ report: 'balance_sheet_pdf', fiscalYearId: ids.aFy }, 'application/pdf', '%PDF'],
        [{ report: 'income_statement_excel', fiscalYearId: ids.aFy }, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'PK'],
        [{ report: 'journal_excel', startDate: '2025-01-01', endDate: '2025-12-31' }, 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'PK'],
        [{ report: 'financial_indicators', fiscalYearId: ids.aFy, format: 'csv' }, 'text/csv; charset=utf-8', ''],
        [{ report: 'fixed_asset_movements', fiscalYearId: ids.aFy, format: 'csv' }, 'text/csv; charset=utf-8', ''],
      ]
      for (const [args, mimeType, magic] of cases) {
        const result = await ok(key, 'export_report', { companyId: ids.aCompany, ...args })
        const { resource, bytes } = fileOf(result)
        expect(resource.mimeType, String(args.report)).toBe(mimeType)
        expect(bytes.length, String(args.report)).toBeGreaterThan(0)
        expect(bytes.subarray(0, magic.length).toString('latin1'), String(args.report)).toBe(magic)
        expect(resource.uri).toMatch(new RegExp(`^kledg://companies/${ids.aCompany}/exports/${args.report}/`))
        expect(result.data).toMatchObject({ report: args.report, mimeType, size: bytes.length })
        expect(result.data.fileName).toBe(resource._meta?.fileName)
        // Never a download link.
        expect(result.text).not.toMatch(/https?:\/\//)
      }
    })

    it('validates with the route schema and keeps the fiscal years of another company out of reach', async () => {
      const key = await apiKey('read')
      const missing = await call(key, 'export_report', { companyId: ids.aCompany, report: 'balance_sheet_pdf' })
      expect(missing.ok).toBe(false)
      expect(missing.text).toMatch(/fiscalYearId est requis/)
      const ofB = await call(key, 'export_report', { companyId: ids.aCompany, report: 'balance_sheet_pdf', fiscalYearId: ids.bFy })
      expect(ofB.ok).toBe(false)
      expect(ofB.text).toMatch(/introuvable/i)
      const format = await call(key, 'export_report', { companyId: ids.aCompany, report: 'financial_indicators', format: 'pdf' })
      expect(format.text).toMatch(/Format d'export inconnu/)
    })
  })

  describe('Qonto documents', () => {
    it('lists and reads the statements without Qonto file URLs, and returns the PDF as a resource', async () => {
      const key = await apiKey('read')
      const listed = await ok(key, 'get_qonto_statements', { companyId: ids.aCompany, getAll: true })
      expect(listed.data.statements).toEqual([{ id: STATEMENT_ID, bankAccountId: 'acc-1', period: '08-2025', file: { fileName: 'releve-aout.pdf', contentType: 'application/pdf', size: PDF_BYTES.length } }])
      expect(listed.text).not.toContain('files.qonto.com')
      const one = await ok(key, 'get_qonto_statements', { companyId: ids.aCompany, statementId: STATEMENT_ID })
      expect(one.data.statement.id).toBe(STATEMENT_ID)
      const invalid = await call(key, 'get_qonto_statements', { companyId: ids.aCompany, statementId: '../accounts' })
      expect(invalid.text).toBe('Identifiant de relevé invalide.')

      const file = fileOf(await ok(key, 'get_file', { companyId: ids.aCompany, source: 'qonto_statement', statementId: STATEMENT_ID }))
      expect(file.resource.mimeType).toBe('application/pdf')
      expect(file.bytes.equals(PDF_BYTES)).toBe(true)
      // Qonto was called with the stored key of company A.
      expect(fetched.some((url) => url.endsWith(`/statements/${STATEMENT_ID}`))).toBe(true)
    })

    it('answers in French when the company has no Qonto connection', async () => {
      const key = await apiKey('read')
      const result = await call(key, 'get_qonto_statements', { companyId: ids.bCompany })
      expect(result.ok).toBe(false)
      expect(result.text).toMatch(/Qonto n'est pas connecté/)
    })

    it('lists the receipts of a transaction and returns a receipt of the company, never one of another company', async () => {
      const key = await apiKey('read')
      const receipts = await ok(key, 'list_qonto_receipts', { companyId: ids.aCompany, transactionId: TX_UUID })
      expect(receipts.data.receipts.map((r: { id: string }) => r.id)).toEqual(['att-a', 'att-b'])
      expect(receipts.text).not.toContain('files.qonto.com')

      for (const attachmentId of [ids.aAttachment, 'att-a']) {
        const file = fileOf(await ok(key, 'get_file', { companyId: ids.aCompany, source: 'bank_receipt', attachmentId }))
        expect(file.bytes.equals(RECEIPT_BYTES)).toBe(true)
        expect(file.resource._meta?.fileName).toBe('recu-a.pdf')
      }
      for (const attachmentId of [ids.bAttachment, 'att-b']) {
        const other = await call(key, 'get_file', { companyId: ids.aCompany, source: 'bank_receipt', attachmentId })
        expect(other.ok).toBe(false)
        expect(other.text).toBe('Justificatif introuvable ou fichier non disponible')
      }
    })

    it('returns the PDF of a Qonto invoice of the company, and "introuvable" for an invoice of another company', async () => {
      const key = await apiKey('read')
      const file = fileOf(await ok(key, 'get_file', { companyId: ids.aCompany, source: 'invoice', invoiceId: ids.aInvoice }))
      expect(file.bytes.equals(INVOICE_BYTES)).toBe(true)
      const other = await call(key, 'get_file', { companyId: ids.aCompany, source: 'invoice', invoiceId: ids.bInvoice })
      expect(other.ok).toBe(false)
      expect(other.text).toBe('Facture introuvable')
    })
  })

  describe('lookup_siren', () => {
    it('looks up the directory for whoever may create a company, and refuses the others', async () => {
      const admin = await apiKey('read', { user: ADMIN })
      const found = await ok(admin, 'lookup_siren', { siren: '552 100 554' })
      expect(found.data).toMatchObject({ status: 'found', company: { siren: '552100554', name: 'NOUVELLE SAS', legalType: 'SAS', headOffice: { postalCode: '75001', city: 'PARIS' } } })
      expect(fetched.filter((url) => url.includes('recherche-entreprises'))).toHaveLength(1)
      expect((await call(admin, 'lookup_siren', { siren: '12345' })).text).toBe('Le SIREN compte exactement 9 chiffres.')

      const owner = await apiKey('read')
      const refused = await call(owner, 'lookup_siren', { siren: '552100554' })
      expect(refused.text).toBe("La création de sociétés est réservée aux administrateurs de l'instance.")
      expect(fetched.filter((url) => url.includes('recherche-entreprises'))).toHaveLength(1)
    })
  })

  describe('create_company', () => {
    it('in validation mode, previews, records a pending action without company, and creates once approved', async () => {
      const key = await apiKey('admin', { user: ADMIN, mode: 'validation' })
      const dry = await call(key, 'create_company', NEW_COMPANY)
      expect(dry.ok, dry.text).toBe(true)
      expect(dry.data).toMatchObject({ dryRun: true, preview: { company: { name: 'Nouvelle SAS', siren: '552100554' }, capital: 1050, creatorBecomesAdministrator: false } })
      expect(await prisma.company.count({ where: { siren: '552100554' } })).toBe(0)
      const pending = await prisma.mcpPendingAction.findUniqueOrThrow({ where: { id: dry.data.actionId } })
      expect(pending.companyId).toBeNull()
      const { listActionsOfUser } = await import('@/lib/mcp/full-control/pending-actions')
      expect((await listActionsOfUser(ADMIN.id)).find((a) => a.id === pending.id)?.companyName).toBe('Nouvelle société')

      expect((await call(key, 'create_company', { ...NEW_COMPANY, actionId: dry.data.actionId })).ok).toBe(false)
      await approve(dry.data.actionId)
      const tampered = await call(key, 'create_company', { ...NEW_COMPANY, name: 'Autre', actionId: dry.data.actionId })
      expect(tampered.text).toMatch(/ne correspondent pas/)
      const done = await call(key, 'create_company', { ...NEW_COMPANY, actionId: dry.data.actionId })
      expect(done.ok, done.text).toBe(true)
      const created = await prisma.company.findUniqueOrThrow({ where: { id: done.data.result.companyId }, include: { fiscalYears: true } })
      expect(created).toMatchObject({ name: 'Nouvelle SAS', siren: '552100554', archivedAt: null })
      expect(Number(created.shareCapital)).toBe(1050)
      expect(created.fiscalYears).toHaveLength(1)
      expect(await prisma.account.count({ where: { companyId: created.id } })).toBeGreaterThan(0)
      expect((await call(key, 'create_company', { ...NEW_COMPANY, actionId: dry.data.actionId })).ok).toBe(false)

      // The grant of every company reaches the new company at once.
      const listed = await ok(key, 'list_companies', {})
      expect(listed.data.map((c: { id: string }) => c.id)).toContain(created.id)
      const audit = await prisma.auditLog.findMany({ where: { action: { in: ['CREATE_COMPANY', 'MCP_FULL_CONTROL'] } } })
      expect(audit.map((r) => [r.action, r.companyId]).sort()).toEqual([
        ['CREATE_COMPANY', created.id],
        ['MCP_FULL_CONTROL', created.id],
      ])
      // A SIREN already on the instance is refused, in the dry run too.
      const again = await call(key, 'create_company', NEW_COMPANY)
      expect(again.text).toBe('Une société avec le SIREN 552100554 existe déjà sur cette instance.')
    })

    it('refuses a connection limited to some companies, and validates like the wizard', async () => {
      const limited = await apiKey('admin', { user: ADMIN, access: { allCompanies: false, companyIds: [ids.aCompany] } })
      const refused = await call(limited, 'create_company', NEW_COMPANY)
      expect(refused.ok).toBe(false)
      expect(refused.text).toMatch(/^Cette connexion est limitée à certaines sociétés/)
      const writer = await apiKey('write', { user: ADMIN })
      expect((await call(writer, 'create_company', NEW_COMPANY)).ok).toBe(false)

      const key = await apiKey('admin', { user: ADMIN })
      const invalid = await call(key, 'create_company', { ...NEW_COMPANY, siren: '1234', shareNominalValue: 1.005 })
      expect(invalid.ok).toBe(false)
      expect(invalid.text).toMatch(/Valeur nominale|SIREN/)
      expect(await prisma.company.count()).toBe(3)
    })

    it("follows the instance policy of a fork: its refusal, its hook, and the creator becomes the company's administrator", async () => {
      const key = await apiKey('admin')
      state.creationRefusal = async () => ({ message: 'Votre offre est limitée à 3 sociétés.', link: 'https://example.test/offres' })
      const limited = await call(key, 'create_company', NEW_COMPANY)
      expect(limited.text).toBe('Votre offre est limitée à 3 sociétés.')

      state.creationRefusal = async () => null
      state.afterCreated = async () => {
        throw new Error('billing down')
      }
      const failed = await call(key, 'create_company', NEW_COMPANY)
      expect(failed.ok).toBe(false)
      expect(await prisma.company.count({ where: { siren: '552100554' } })).toBe(0)

      state.afterCreated = null
      const done = await call(key, 'create_company', NEW_COMPANY)
      expect(done.ok, done.text).toBe(true)
      const companyId = done.data.result.companyId
      const member = await prisma.member.findFirstOrThrow({ where: { userId: OWNER.id, organization: { companyId } } })
      expect(member.role).toBe('companyAdmin')
      // The owner's grant of every company reaches it at once.
      expect((await ok(key, 'list_fiscal_years', { companyId })).data).toHaveLength(1)
    })
  })

  describe('archive_company and restore_company', () => {
    it('archives (read-only, hidden), then restores, for an instance administrator', async () => {
      const key = await apiKey('admin', { user: ADMIN, mode: 'validation' })
      const dry = await call(key, 'archive_company', { companyId: ids.aCompany })
      expect(dry.data).toMatchObject({ dryRun: true, preview: { company: { id: ids.aCompany, archived: false } } })
      await approve(dry.data.actionId)
      const done = await call(key, 'archive_company', { companyId: ids.aCompany, actionId: dry.data.actionId })
      expect(done.ok, done.text).toBe(true)
      expect((await prisma.company.findUniqueOrThrow({ where: { id: ids.aCompany } })).archivedAt).not.toBeNull()

      const auto = await apiKey('admin', { user: ADMIN })
      const write = await call(auto, 'create_journal', { companyId: ids.aCompany, code: 'XX', label: 'Divers' })
      expect(write.text).toMatch(/archivée/)
      const visible = (await ok(auto, 'list_companies', {})).data.map((c: { id: string }) => c.id)
      expect(visible).not.toContain(ids.aCompany)
      const all = (await ok(auto, 'list_companies', { includeArchived: true })).data
      expect(all.find((c: { id: string }) => c.id === ids.aCompany)?.archivedAt).toEqual(expect.any(String))
      // Reading an archived company stays possible.
      expect((await ok(auto, 'export_report', { companyId: ids.aCompany, report: 'journal_excel' })).ok).toBe(true)

      const restored = await call(auto, 'restore_company', { companyId: ids.aCompany })
      expect(restored.data).toMatchObject({ executed: true, result: { success: true } })
      expect((await prisma.company.findUniqueOrThrow({ where: { id: ids.aCompany } })).archivedAt).toBeNull()
      const audit = await prisma.auditLog.findMany({ where: { action: { in: ['COMPANY_ARCHIVED', 'COMPANY_RESTORED'] } } })
      expect(audit.map((r) => r.action).sort()).toEqual(['COMPANY_ARCHIVED', 'COMPANY_RESTORED'])
    })

    it("refuses a company administrator who is not an instance administrator, like the route", async () => {
      const key = await apiKey('admin')
      for (const tool of ['archive_company', 'restore_company']) {
        const result = await call(key, tool, { companyId: ids.aCompany })
        expect(result.text, tool).toBe("Action réservée aux administrateurs de l'instance.")
      }
      expect((await prisma.company.findUniqueOrThrow({ where: { id: ids.aCompany } })).archivedAt).toBeNull()
    })
  })
})
